### ISSUE TITLE
What output formats do we want to support in VF?

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#125]
Json-ld was our initial intent.  We've created some owl for vowl pictures.  YAML has been suggested  for examples.  We would want to really support any RDF related format I think.

We also could consider supporting other technical layers than LOD, like the experiments in Patchwork etc.  In this case, we would want an additional format.

**Comment by elf-pavlik** [comment]
https://www.w3.org/TR/rdf11-new/#section-serializations

![rdf serializations](https://www.w3.org/TR/rdf11-new/serialization-formats.png)

> Json-ld was our initial intent. We've created some owl for vowl pictures.

You've created some .ttl (Turtle) which uses OWL terms, that turtle has automatic conversion to JSON-LD and any other RDF format. You could have written it in JSON-LD, convert to Turtle and than use it in WebVOWL, all RDF serializations have standard tools in popular programming languages to convert from one to another.

> We would want to really support any RDF related format I think.
:+1: 

> YAML has been suggested for examples. 

#122 clearly states "JSON-LD compatible subset of YAML", so we can automate conversion to JSON-LD and get the RDF this way

> We also could consider supporting other technical layers than LOD, like the experiments in Patchwork etc. In this case, we would want an additional format.

I think @ahdinosaur needs to propose something since he explores that possibility. I would like that we keep graph data model in mind as I explain in #123

**Comment by fosterlynn** [comment]
Conclusion in meeting: 

We will support any LOD format.  (At least, and maybe non-LOD formats, TBD.)

We can make examples in YAML because it is easier to hand-code, and can be transformed to JSON-LD.  From JSON-LD, we can get to RDF, then to any LOD format.  We can make examples in JSON-LD if that is easier because for example they are generated.

**Comment by ahdinosaur** [comment]
i'm not committed to RDF or JSON-LD, i find them quite overly complicated and more pain than gain. but happy to go with the group for now until i have a better alternative, as long as we point our focus on describing the vocabulary for humans instead of being a specification for cyborgs. :)

**Comment by bhaugen** [comment]
@ahdinosaur I thought you liked yaml. Did I misunderstand?

Regardless, I want to support your direction as well as the LOD direction. I think we will end up with a range of descriptions from plain text glossary to I hope some interactive explorers to working code examples to a variety of output formats, which I hope can be easily translated from one to another.

**Comment by fosterlynn** [comment]
@ahdinosaur I second Bob's comment - I'd like to be able to define VF as examples and understandable pictures for any software interoperability technical scheme that gains traction.  Seems like things haven't shaken out there at all yet.  Although I'm quite happy doing LOD on top of the base non-denominational model right now.
