### ISSUE TITLE
Name for rea:EconomicEvent

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#155]
The main class I think we don't have a good name for in non-release 0.0 (aka September sprint) is rea:EconomicEvent.  Unclear if we want one name for all events or a name for process related events and one for transfer events.  Also there is still discussion on if events can stand on their own.  We have said transfer events can be on their own.  We have disagreement on process type events. 

Here are some things we have called at least the process related events:
vf:IPOEvent (current one)
vf:InputOrOutput
vf:ResourceEvent
vf:Flow
...and probably several more....

**Comment by bhaugen** [comment]
For accounting and economic analysis purposes, it will be necessary to be able to treat all economic events as variations on the same concept, with at least some common properties. That was the genius of REA:EconomicEvent. Economic Events are the distilled essence of REA.

**Comment by fosterlynn** [comment]
from @pmackay vf:FlowEvent

**Comment by fosterlynn** [comment]
and of course there is vf:EconomicEvent, which I am liking more and more :)

**Comment by fosterlynn** [comment]
vf:ValueFlowEvent?

**Comment by pmackay** [comment]
Question about vf:FlowEvent - are there any kinds of events that this could represent that would not be "flows"? Where EconomicEvent (being more general) is better?

**Comment by fosterlynn** [comment]
>Question about vf:FlowEvent - are there any kinds of events that this could represent that would not be "flows"? 

Probably not, at least on a conceptual level.  One possibility is a transfer, which in our latest model is more incidental to the main flows of resources, but there is still some kind of flow between agents there.  Also, some of us (but not all) think we will want to support work events (and possibly other kinds) where the process is not recorded, usually "overhead" type things, where the usefulness is so spread out over other processes in a context that it is not worth thinking about processes and resource outputs, even though they are there.  But I would still consider those parts of flows. 

The term "flow" has generated some confusion because economic events represent more of an event in the trigger sense, where they record an impact on a resource and an impact on a process, but don't actually contain a resource themselves which is flowing along.  It's more like they are triggering a flow.  They are an edge where you can imply an arrow.  Or something like that.  :)

**Comment by elf-pavlik** [comment]
> Unclear if we want one name for all events or a name for process related events and one for transfer events.

For 0.0 I would prefer not to try decide on that and only focus on IPO events. Once we pin them down little more we can see how to align them with events which don't affect the resource but only rights to the resource (agent <-> resource relationships).

**Comment by fosterlynn** [comment]
@elf-pavlik don't worry, no decisions will be made without everyone.  But let us carry on in background in the meantime without affecting 0.0 trajectory. Any progress would be nice and can get folded in when you are ready. :blush:

We could go either direction: one name for all rea:EconomicEvents, with the vf:action further defining them; or we could have one layer of subclassing for process related and transfer related events.

**Comment by fosterlynn** [comment]
>I think VF does need to look really closely at stuff such as this W3C conception of "Activity", along the lines with VF's concerns about events/ observations/ reports. And frankly, I'd rather if VF used "action", "interaction" and/or "activity" than "event" for such things, because "event" is a very deeply useful term for social organization and planning of activities. Of course I realize the REA model is Resource Event Agent, but maybe we (or at least some of us) should be thinking instead of Resource Action Agent.

@gcassel I'm repeating your comment over here in the "name the event" issue.  I do want to get this nailed down as we continue to work, and am hoping something magically strikes us as perfect.  :smile: 

The W3C "activity" as in "activity streams" is broader than economic events.  And I agree that this meaning of "event" is possibly more tech-ish in its origin.  

"economicAction"?
"resourceAction"?
"resourceChange"? ( @bhaugen suggestion this morning)
"economicActivity"?
"resourceActivity"?

**Comment by gcassel** [comment]
I should disclose my conflict of interest on this subject, LOL, because in my extensive research for Agreement-Based Organization, I decided that "Event" is a very basic *type of subject* for people to agree or to disagree on.   I use this definition [in ABO](https://docs.google.com/document/d/1c_xWEIay-2jyJ3Rqb6OgTxoZBJfjNW4d6w6ukXyeJk4/edit#heading=h.ecrw0mstf0x2) : "Events indicate occasions, of any duration, during which special conditions and/or activities persist."

I think that that precise meaning of "Event" is more flexibly  useful for *social and economic* **planning** than the term "Activity" could ever be-- because events are often described as *special conditions*, without directly describing the *activity* which the special conditions pertain to.  For instance, "50% off all ladies shoes on Tuesday" or something such.

Anyway:   I think that "Activity" means an identified *type of action* or *type of interaction*, doesn't it?   Such as (quite generically) "we're going kayaking on Saturday" or "vendors sell goods to the public from these stalls".     -- And with that in mind, I believe that economic accounting is about describing *specific actions and interactions*, not activities or events.

**Comment by fosterlynn** [comment]
>I should disclose my conflict of interest on this subject,

hahaha good to know!
