### ISSUE TITLE
Process vs Service example

### ISSUE THREAD

**Issue by djodjoni** [valueflows/valueflows#181]
lets take cooking for example, is this a ServiceResource or is it a Process?

**Comment by bhaugen** [comment]
If you mean to take some ingredients and cook some food to eat, that's a process. Or often, a chain of several processes.
Example: https://github.com/valueflows/valueflows/blob/master/use-cases/best-whole-wheat-bread.md

**Comment by djodjoni** [comment]
this is clear, but isn't that a Service Resource as well for example cooking, where you can have planning, commitment, events, fulfilment etc. ?

**Comment by djodjoni** [comment]
One other thing is delivery. On the other thread you have mentioned it might need a ProcessTemplate but isn't that a Service actually with a serviceTemplate i.e. ResourceTemplate ?

**Comment by fosterlynn** [comment]
Services are tricky.  :sweat_smile:   We've been thinking about them off and on for a while.

Although the cooking example I don't quite understand.  I would think that cooking would be the process and the output would be some prepared food, not a service.  There would probably be some work input, or maybe even a service input, depending on how you want to look at it.  And ingredient inputs, etc.

Or maybe it could be a service if someone does cooking for a family say, and it isn't important to know the food output, just that they provide that service, maybe for x hours a week or whatever.

We want to have our usual input-process-output pattern work for everything.... really more like resource-inputevent-process-outputevent-resource.  This works well to create value flows.  Outputs from one process are hooked up to inputs to the next process through resources instead of directly.  This looser coupling allows you to for example make 10 widgits, and consume 5 of them in one process and 5 in another process.

But sometimes there isn't a tangible resource produced; or even if there is one, it isn't important to record that.  Could be a service, could be something that is just too much trouble to inventory.

So service - in practice, when you execute a process that delivers a service, by the end of the process it is a done deal, and the process and output seem to be the same thing.  Maybe thus your question?  So creating a service output seems kind of overkill. Our newest model for exchange can handle that because it references only events, not resources.  But if you want the service as an output of one process and the input to the next process, it is more trouble. Could create a service resource, which immediately goes to 0 quantity because it is gone, or could use the same event as output and input to the nest.  We are still very much in unresolved discussion on this, see #173 .

**Comment by djodjoni** [comment]
>  would think that cooking would be the process and the output would be some prepared food, not a service. 

> Or maybe it could be a service if someone does cooking for a family say, and it isn't important to know the food output, just that they provide that service, maybe for x hours a week or whatever.

By those 2 I understand that you assume service does not have an output, but every service do have some output some not material some not even tangible. A service IMO involves a process or many processes. A service may involve material, intellectual or any other product. And as for the resulting product W it can be part of Material A,B and Service X. So again for me a process is just part of a service.

**Comment by bhaugen** [comment]
> By those 2 I understand that you assume service does not have an output, but every service do have some output some not material some not even tangible. A service IMO involves a process or many processes. A service may involve material, intellectual or any other product. And as for the resulting product W it can be part of Material A,B and Service X. So again for me a process is just part of a service.

@djodjoni can you please give some examples of what you are talking about? Because I am not following what you are saying, and you may not be following what we are saying. Something like the examples here?
https://github.com/valueflows/valueflows/tree/master/use-cases

Then we can detail them out in terms of inputs, processes, and outputs.

**Comment by djodjoni** [comment]
The question is simply how do you differ from those. I can clearly see that you are trying chaining inputs, outputs and processes in the middle.However What is a Process? Who does it? Isn't that actually a service? 

And I think I understand you point, correct me if I am wrong (or nod otherwise :)
So in practice everything can be in->(process)->out , however you see a service as something that may produce nothing (IMO this is perfectly fine and valid for processes also)

for example https://github.com/valueflows/valueflows/blob/master/use-cases/broken-bike.md

There several things which doesn't fully match my understanding:
> ResourceTypes
    Bicycle
    Bike shop - this could be Bike shop Service

IMO Bike shop -> Bike shop Service

> Resources
    John’s bike with a dodgy brake
    Dave’s bike shop that provides a repair service

IMO Dave’s bike shop that provides a repair service ->  Dave’s bike shop repair service

because  then you have :
> Inputs 	Process 	Output
Equipment 	Repair 	Equipment (repaired)
Parts 		
Repair work 		


which could be valid, but I was not duplication the service as in my view it includes the process so I would say:

equipment,parts->(Repair Service)->Equipment (repaired)

And this is precisely because all services for me are some kind of a process with input(s) and output(s), where you separate those and indeed looks more clear.

Anyway I hope I understand your approach now.

Then I have another set of questions:
1) why Process does not reference directly to the Resources it uses ?
2) Isn't exchange a process?

**Comment by bhaugen** [comment]
I'll try to answer a few questions. Might not answer them all.

> What is a Process? 

A Process takes input resources and turns them into output resources.

> Who does it?

Whoever is working on the process. Processes almost always have work inputs.

> why Process does not reference directly to the Resources it uses ?

Processes reference the Resources they require, by means of Input Plans, and then the Resources that were consumed or used, by means of Input Events.

> Isn't exchange a process?

An exchange is similar to a process in that it is an economic interaction, but has different behaviors from a process. 

An exchange trades some resources from one agent for some resources from some other agent. The resources themselves are not changed in the exchange.

Resources are often changed in processes, and often new resources are created.

**Comment by bhaugen** [comment]
One more thing about a Process, that people who do not understand or resist the ideas of Types or Templates sometimes miss, is that a Process that happens repeatedly usually has a Process Template, that tells people what to do. This is usually part of a Recipe. As in:
https://github.com/valueflows/valueflows/blob/master/use-cases/best-whole-wheat-bread.md
http://www.smithsonianmag.com/arts-culture/what-makes-whole-grain-bread-so-hard-to-bake-63878

By the way, this looks ~almost~ perfect:
> equipment,parts->(Repair Service)->Equipment (repaired)

Except the Repair Service is a Repair Process and the repair work (Dave's work) is an input to the Repair Process. So in I->(P)->O terms, it would go:
equipment,parts, Dave's repair work->(Repair Process)->Equipment (repaired)

Does that make sense to you?

**Comment by fosterlynn** [comment]
Adding on a little :)

>however you see a service as something that may produce nothing (IMO this is perfectly fine and valid for processes also)

We think about it more like: there is a process that produces a service (instead of nothing) which is somewhat different than a product; a service could be a haircut, which is not nothing, but is different enough from a product that we call it a service.  A process can produce a product(s) or a service(s) or both or neither.

 >>why Process does not reference directly to the Resources it uses ?

>Processes reference the Resources they require, by means of Input Plans, and then the Resources that were consumed or used, by means of Input Events.

The input and output events are edges, needed to link resources and processes, and to define the important information about how/what resources are input or output to/from the process.  For example, a resource could be 20 bolts.  The event says that 5 of these bolts are consumed in the process.  The event will decrement the resource so now it is 15 bolts.

P.S. I'm working on mapping your ttl to VF, I hope to have something useful tomorrow morning, because after that we will have guests for the weekend.

**Comment by djodjoni** [comment]
@fosterlynn  @bhaugen  Thanks for explanation , things are more clear :)

one other thing I noticed :

> An exchange trades some resources from one agent for some resources from some other agent. The resources themselves are not changed in the exchange.
Resources are often changed in processes, and often new resources are created.

What is a Transportation then ? It seems like an exchange but @bhaugen  mentioned in the past it could be a process. Infact it is not a simple exchange because it include resources like vehicle, gas, etc.

**Comment by fosterlynn** [comment]
Transportation we decided was best as a process, even though the resource itself is unchanged, because the change of location adds value to the resource, in that it is positioned for some other next step.  And yes, there certainly are inputs to transportation.

**Comment by djodjoni** [comment]
Ok clear thx for clarification! I think i can close this and proceed practicing with experimets and examples :)

**Comment by elf-pavlik** [comment]
> What is a Transportation then ?

From the perspective of agent *receiving* transportation service, we may possibly just need *load* & *unload* events on transported resource to represent the 'transportation service' - something that exchange may include.

> An exchange trades some resources from one agent for some resources from some other agent. The resources themselves are not changed in the exchange.

In recent exploration started by @fosterlynn we find that we may have exchanges not based on resources but just events. For example exchanging work for work, or work for usage etc.
Same may work for transportation, one could exchange something for 'transportation service' represented just by *load* & *unload* events with no resource need at all to represent 'the received service'
