### ISSUE TITLE
vf:Agent or foaf:Agent

### ISSUE THREAD

**Issue by djodjoni** [valueflows/valueflows#182]
shall we have a custom vf:Agent or shall we just reference to the well know foaf:Agent and its subclasses

**Comment by pmackay** [comment]
Pragmatic reuse seems preferable IMHO, so can VF use other vocab's classes, properties where possible? I see the ESS Global spec did this somewhat, and I really like how the Popolo Project [approached reuse](http://www.popoloproject.com/specs/#standard-reuse).

**Comment by fosterlynn** [comment]
Yeah, if we can do "pragmatic reuse" that is great.  Good Relations did this too.  And yes, the Popolo Project documention is very good.  I'll have to look at their semantics, to see how they formally do mapping or reuse.

@djodjoni what is your opinion?  (implied but not stated :blush:   )

**Comment by djodjoni** [comment]
Implied indeed and even if a statement here could be redundant :) I am also for "pragmatic reuse" this what I try to apply for the food vocab i'm doing :)

**Comment by fosterlynn** [comment]
>Implied indeed and even if a statement here could be redundant :) I am also for "pragmatic reuse" this what I try to apply for the food vocab i'm doing :)

thanks just making sure....  :)

**Comment by fosterlynn** [comment]
OK, we decided (I think) to just use foaf straight out for agents, right?  As opposed to referencing other vocabs as sameAs?  I didn't do this in the current round of doc for gitbook, I can change it.

Although I was noticing yesterday that foaf:Group is not what we have really.  To them it is any grouping or categorization of people, like "all the monarchs of England", not necessarily something that people have actually organized.  Maybe vf:Group is a subclass of foaf:Group?  This is a bit true for foaf:Agent, which is broader than economic agents, but that seems more like close enough somehow?

Now @djodjoni raises the same question for common properties like url, name, image.

Some of these may only apply to one of our classes, seems good to have that domain defined so it shows up there.... I don't know if we can do that if it is foaf?  The UML can always show everything, but that is really secondary documentation.

Please give your opinions, LOD people, I am traveling in the dark here.

**Comment by pmackay** [comment]
>OK, we decided (I think) to just use foaf straight out for agents, right? 

+1

Could redefine Group if it has tighter semantics.

>Some of these may only apply to one of our classes, seems good to have that domain defined so it shows up there.... I don't know if we can do that if it is foaf?

Not sure I quite understand this, can you expand a bit?

**Comment by djodjoni** [comment]
> Some of these may only apply to one of our classes, seems good to have that domain defined so it shows up there.... I don't know if we can do that if it is foaf?

I am also not sure if I understand this the right way, however if you say we need more restrictions we can do that using foaf for example, but I would rather be less restrictive at least in the first drafts so to see how ppl would make use of that eventually.

**Comment by bhaugen** [comment]
For VF, we need to know if a group is an agent or not. As in, has agency, can make agreements, can affect economic resources, etc. Or if it is a motley collection of whatever. James Odell has this concept of Agentified Groups or Non-Agentified Groups that might be useful. (Not pushing the names, but Odell is actually a collaborative person and might talk to us if we wanted.)

**Comment by elf-pavlik** [comment]
> For VF, we need to know if a group is an agent or not.

Currently we may actually only care about the agency aspect (foaf:Agent) and we may only need to go more specific for *work* which only an individual can do (foaf:Person). I don't think we currently have anything specific about groups and we keep thinking about organizations. IMO for now we only need foaf:Agent & foaf:Person so groups and organizations can use foaf:Agent. We also don't seem to use direct relation foaf:member or org:hasMember or vcard:hasMember so I wouldn't worry about anything more specific for groups than foaf:Agent until we further clarify the requirements ...

**Comment by bhaugen** [comment]
@elf-pavlik are you claiming that we do not need groups that are agents?

**Comment by fosterlynn** [comment]
>Currently we may actually only care about the agency aspect (foaf:Agent) and we may only need to go more specific for work which only an individual can do (foaf:Person). I don't think we currently have anything specific about groups and we keep thinking about organizations

I think people will want to have "not a person", even if it doesn't show up in a direct connection in the vocab.  And for that, it seems to me that Group and Organization are the key ingredients.  Some groups also like to define their own, and if we have Person, Group, and Organization, they have something to subclass from that pretty much covers it I think.

**Comment by elf-pavlik** [comment]
I think that for now enough to have foaf:Agent and foaf:Person. We don't have anything specific about groups / organizations so using foaf:Agent for them seems fine to get started.

>  Some groups also like to define their own, and if we have Person, Group, and Organization, they have something to subclass from that pretty much covers it I think.

Since VF doesn't define anything specific about groups and organizations, anyone can subclass foaf:Agent directly, we don't have need to do it in VF.

When it comes to defining a group, most vocabs besides having come class, also define property representing membership - foaf:member, org:hasMember (org:memberOf), vcard:hasMember. Suggesting foaf:Group but not foaf:member may come as confusing attempt to reuse FOAF. IMO until we feel ready to tackle the membership aspect we can keep it safe with starting to using foaf:Agent for groups / organizations.

**Comment by bhaugen** [comment]
I can't do the vocabulator without group agents. Many of our use cases require them. 

Likewise all the work I have done for the past 20 years leading up to VF requires them.

VF has always talked about group agents. Group memberships were one of the first we worked on, for Holodex. Absence of groups would be a show-stopper for me.

**Comment by elf-pavlik** [comment]
I understand that you need a way not to just mark agent as foaf:Agent but specify it as 'group agent' (not foaf:Person). At the same time you do NOT need to specify which agents in particular make this group a group (eg. foaf:member)?

**Comment by bhaugen** [comment]
I need the membership relationships, too.

**Comment by fosterlynn** [comment]
>At the same time you do NOT need to specify which agents in particular make this group a group (eg. foaf:member)?

I don't think we need member to have groups since we have a flexible relationship available for people that can include any kind of relationship.  Especially for a release 0.1.  If we want to go that way, I can add it to the list of stuff coming in the Status page.

But I'm also fine getting member back in there, and doing the other ones we talked about too (part of / sub / child for example).  I think I took member off of the diagram awhile back because it wasn't modeled right on the UML side, and we never got it back, although it was meant to be temporary.  But we also talked about needing more than membership to give a basic scope of types of relationships, it didn't seem right all by its lonesome.

And btw, it is quite possible to need Group but not need to specify its members because the Group can act as an agent for itself, hiding its governance inside.  For example, Matthew had a use case where when people within different timebanks exchange with each other, the personal identity was hidden and it was recorded as between the timebanks.

**Comment by bhaugen** [comment]
I don't care what you call it. I need to be able to associate individual agents with groups. If this is a naming argument, please get me out of it by saying I will be able to say that some number of agents can have relationships with some other agent that can act in a group-like manner.

I would like to reserve naming arguments for those rare cases when I might want to object to a name, and will try to minimize them. So if what I am asking makes sense on some human communication level, please respond in kind.

**Comment by fosterlynn** [comment]
@bhaugen sorry to confuse things.  This is not a naming argument.  And don't worry, nobody has suggested removing vf:relationship, which gets you any type of relationship you want between agents of any type.

**Comment by elf-pavlik** [comment]
> I don't care what you call it. I need to be able to associate individual agents with groups.

Using vf:Relationship you can associate instances of foaf:Agent, so individuals with individuals, individuals with groups and groups with individuals. At the same time we didn't agree on relationship which would mean 'a member of a group' so currently you could have group agent with some kind of 'customer' or 'fan' relationships to individuals but you couldn't tell which other agents make this group a group agent and which agents have some 'other' relationship with that group agent. Most vocabs which have concept of a group, also have property which clearly relates a group to it's members. I mostly prefer no to rush with adding groups & organizations since we seem far from agreement how to represent such 'membership' aspect, and if we reuse group concept from some existing vocab but don't reuse 'membership' relation for the same vocab we most likely will cause a lot of confusions.

I don't remember why we didn't reuse https://www.w3.org/TR/vocab-org/#class-membership as n-ary relation between agents. Possibly we could align it with *vf:Relationship* (which mimics *as:Relationship*)

```ttl
org:Membership rdfs:subClassOf vf:Relationship.
org:member rdfs:subPropertyOf vf:object .
org:organization rdfs:subPropertyOf vf:subject .
```

We would need to take a look at how they define Role and how this would align with *vf:relationship*.

**Comment by fosterlynn** [comment]
@elf-pavlik I understand your point about using other vocabulary for Group implying that we should use their *membership* structure also, or it might be confusing.

If that is the case, then I think we will have to have vf:Group.  None of the relationship structures I have seen give the simplicity and flexibility I think we need.

>I don't remember why we didn't reuse https://www.w3.org/TR/vocab-org/#class-membership as n-ary relation between agents.

They define membership as between a foaf:Agent and org:Organization.  I think too narrow.  And we haven't even agreed on including Organization, although I still think we want it called out explicitly.

Although I notice that they define their own membership structure, they don't use foaf's even though they do use foaf:Group.  So maybe it isn't so confusing?

I read the definition for foaf:Group the other day, and I think it would be OK for us, even though it probably is more broad - its focus still gets at our main needs.  (I was reading the ontology book, and it had that example of a foaf:Group of monarchs of England, so I started thinking it was out of bounds for us.  The monarchs of England in fact don't have any agency at all as a group as far as I can tell.)

I'm fine with going with all vf: in the agent hierarchy for release 0.1 if that is the path of least resistance for us, kind of the "let's think about it more carefully later".  Or I'm fine with going with foaf: for Agent, Person, Group, and keeping our relationship structure, also "let's think about it more later".  Or from this recent discussion, I see something like:

Agent
-- Person
-- Group
---- Network
-- Organization

**Comment by fosterlynn** [comment]
>At the same time we didn't agree on relationship which would mean 'a member of a group' 

I think we agreed on it in principle, just didn't ever get it modeled so we liked it.  I think we agreed there are probably a handful of useful kinds of agent relationships that we should call out, including membership, sub of, etc. - but we never made it happen.

**Comment by elf-pavlik** [comment]
I think we could start just with
Agent
-- Person
-- Organization

As I suggested in https://github.com/valueflows/valueflows/issues/204#issuecomment-287632578 Organization seems to cover all the ways agents may want to organize themselves. Group and Network seem just confusing and from my experience people sometimes tend to call their organizations as networks just to make it sound more significant. Actualy schema.org has only Person and Organization, no Groups, Network, Circles, Triangles or whatever else people may want to call the way they organize themselves.

**Comment by elf-pavlik** [comment]
https://github.com/valueflows/valueflows/issues/204#issuecomment-288164977
> @fosterlynn: That's fine with me. Let's keep Group, or GroupAgent

Currently we only need to distinguish between a Person and Non-Person. Organization can cover both 'organized groups' (not organized groups very unlikely have agency) as well as Non-Person agent where at any moment in time only single Person stays involved.

I don't see need for both Group & Organization, in practice nothing stops Group from having just one 'member' at any moment in time.

**Comment by fosterlynn** [comment]
I still disagree.  Which vocab's Organization would you like to use?  Let's check the definition.

And let's see if there is a definition for Group that has just one Person member.

**Comment by elf-pavlik** [comment]
AFAIK none of vocabs/ontology include formal restrictions that prevent groups from having even 0 members:

```ttl
<https://empty.example/> a foaf:Group .
```

**Comment by ahdinosaur** [comment]
> Agent
> -- Person
> -- Group
> ---- Network
> -- Organization

:+1:

previous discussions:

- https://github.com/valueflows/valueflows/issues/159
- https://github.com/valueflows/agent/issues/68
- https://github.com/valueflows/agent/pull/66

i think it'd be great to have a description next to each to disambiguate the word in general with our specific definition. like when @fosterlynn [described the difference between Group and Organization](https://github.com/valueflows/agent/pull/66#issuecomment-226045871) i found it to be helpful.

**Comment by elf-pavlik** [comment]
@ahdinosaur you may want to take a look at https://github.com/valueflows/valueflows/pull/206

**Comment by fosterlynn** [comment]
Closing.
