### ISSUE TITLE
Help rewrite the first 2 sentences of the gitbook

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#200]
> ## A vocabulary for distributed economic systems

> Value Flows is a set of common vocabularies to describe flows of economic resources of all kinds within distributed economic ecosystems.

Or, in context: https://valueflows.gitbooks.io/valueflows/content/

"Economic systems" is both too big and too generic. Although I''d like us to get there, too grandiose for now.

Economic networks, as in one of the previous intros, is better, but still too generic. Same for economic ecosystems: although evocative, does not differentiate from e.g. the Apple or Android ecosystems.

I feel like we should upfront appeal to alternative/solidarity/cooperative/next/some different economic networks, altho the vocab would also work for local small business networks.

What is a clear, simple, and compelling way to say that?

Or do you disagree?

**Comment by djwesto** [comment]
Hi Bob,

@pmackay pointed me to this post because we're just discussing terminology for users at the moment so are facing the same challenges of what to call things for non-techies.

I wonder if it might help to think about how to shape this wording if you were to be a bit more specific about who you're hoping will read this and who you're trying to engage with. For us we currently have three key personae:

* Analysts and decision-makers working at local government level
* Local business leaders and sustainability consultants
* Local community group leaders

Each of them will probably have a different take on things. But there are core concepts which should make sense to all of them.

If we take the current meaning of an `economy` and a `network` are those two concepts similar enough that you only need to say one of them. For ValueFlows, aren't these two concepts reasonably synonymous?

* Economic network
* Value ecosystem

Or do you see them both having two separate meanings?

**Comment by bhaugen** [comment]
@djwesto thanks for popping in. 
> For ValueFlows, aren't these two concepts reasonably synonymous?
> * Economic network
> * Value ecosystem
> Or do you see them both having two separate meanings?

I think they are reasonably synonymous, but tend to be used by different people, and have different nuances. I see "value ecosystem" used a lot with groups of businesses who share some common substrate, like a technology platform: for example, the Android or iPhone ecosystems. In other words, in use, it seems to be a narrower concept. I see "economic network" used more broadly.

But I have not done a systematic survey.

I think, at this stage, VF wants to attract software developers who are interested in the experiments variously named solidarity-cooperative-next-post-capitalist economy, which is why I would like to get some hint at that in the lead sentences. We also get some interest from people who are organizing projects or just very interested in that field, but are not software developers, but they would probably be engaged by the same phrasing.

Anybody else got a different view of the VF "audience" at this stage of the game?

**Comment by fosterlynn** [comment]
>Anybody else got a different view of the VF "audience" at this stage of the game?

Makes sense to me.  I do think that non-developers who are struggling with software for their groups can be an audience, but yes they can get engaged with the same wording as for devs.

I would include transitional in addition to the solidarity-etc-etc stuff.

**Comment by fosterlynn** [comment]
...and thanks @djwesto , that is a good way to think about it.

**Comment by fosterlynn** [comment]
Closing this, if you want to further tweak the wording, please comment in current PR, or open a PR yourself against it, thanks!
