### ISSUE TITLE
Network of Networks or The Worldwide Network with subnets?

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#204]
Looking at those illustrations
![network-elio-cropped](https://cloud.githubusercontent.com/assets/876431/24074802/4a958404-0bd5-11e7-867f-68867dae4cd9.jpg)

![network-of-networks](https://cloud.githubusercontent.com/assets/876431/24074803/4fbb94fa-0bd5-11e7-9269-db087957dd4c.png)

I remember conversation started by James Lewis https://www.facebook.com/groups/networkofnetworks/permalink/303918229774545/?match=YWxiZXJ0bw%3D%3D where he argues against 'network of networks' and explaining that in the end we just have a network. I agree with this perspective and see it more precise to talk about 'global economy' ([Spaceship Earth](https://en.wikipedia.org/wiki/Spaceship_Earth)) as 'The Network' where we can find all kinds of distinct subnets. At the same time any peer in 'The Network' can participate (or not) in any number of those subnets.

I propose to switch our terminology from Network of Networks to The Worldwide Network with all kinds of subnets. And work with definitions of 'subnet' and 'group agent'. Since group agents can have membership relationship to some broader 'group agents' when do we just have a group agent and where do we already have a network? Should we also have Groups of Groups and Networks of 'Networks of Networks' ;)

I don't have sources for those images I would like to help with making variants which illustrate The Worldwide Network where one can distinguish all kinds of 'subnets'.

**Comment by fosterlynn** [comment]
@elf-pavlik I'm not sure what would be different semantically between the two ways you posed this, network of networks, or worldwide network with sub-nets.  But I do want to comment a little about this philosophically, or ideologically if you will.

I think we humans do tend to build up our connections from the small to the larger (and this will become more important as climate change takes its toll).  I am part of many groups and these define my life more than my individuality within the species.  I think this is true for many people.  Or in any case, it is one valid way to look at the structures of humanity.  

Think about indigenous tribes, who have been groups for a long time, but since economic and cultural imperialism has tried to dismantle them, have made special efforts to maintain their group-ness and preserve their cultural heritages.

Groups organize themselves around shared needs, values, skills, etc.  I don't want to join Sensorica, it is a place for people with skills I don't have, along with a desire to work on sensors and organize themselves as an OVN.  (Although Mikorizal has a peer relationship with Sensorica.)  You may want to join a community who wants to live and share a certain way among themselves.  We get our meat monthly from a local CSA who raises it as part of a permaculture farm.  The people who belong to the CSA, and the farmers, are an economic group.  Although you may validly differ, I want to get my food that way, I personally don't want to continually broadcast intents when I need something - this adds stability to our household group, and stability and shared risk for the farmers.  We talked yesterday to some local people who want to organize a transportation multi-stakeholder coop to transport food from small farmers to small food coops, buying clubs, etc. around the state.  This is a need of only small producers and retailers and will work only within a specific geographic boundary, also will involve a lot of logistical planning, and so won't be a freeform loosely held group.  Although freeform loosely held groups are totally valid too for other kinds of needs - I have really enjoyed the experience of ValueFlows as a loose global network.

All of these example groups can act as agents, and interact with other people and groups, but they also all have a membrane that keeps their identity and their usefulness intact, and allows them to govern themselves as they see fit for the group purpose, even as their membership changes.

This is not to deny that everything eventually connects, and that flows can trigger widely through networks or sub-networks.  

But basically to think there a global network and want to create sub-networks within that creates an inherently hierarchical top-down thought process.  The only pervasive global economic network that exists today is neo-liberal capitalism.  Recently the Mutual Aid Network and FairCoop met to discuss ways they might collaborate economically.  This was a meeting of peer networks exploring building a larger network connection.  Neither wants to become a member of the other, just look at useful ways to collaborate.  I think this is how it happens and how we want it to happen, not from the top to the bottom.

**Comment by fosterlynn** [comment]
@elf-pavlik Now more to your specific points.  :) 

>Since group agents can have membership relationship to some broader 'group agents' when do we just have a group agent and where do we already have a network?

Networks are a kind of group, no?  I would be fine with defining Network as a subclass of Group so that we call it out explicitly.

Then I'll move over to the other issue #182 .

**Comment by gcassel** [comment]
>Networks are a kind of group, no?

Networks are *groups of agents*.  In many networks, most of those agents are autonomous, equal peers with respect to participating in the network.   Those agents often have no formal relationship, other than their ability to participate.   

I believe that the term "group agent" should be reserved for groups which hold (often small, strict) domains of formal authority which are explicitly accepted by the members of those groups.  Looking inside such a group agent (i.e., zoomed-in Level of Detail) you see an "organization" of individuals.

It should be noted that most networks of autonomous participants are at least partially subject to one or more regulatory bodies.  Sometimes they don't even realize it.  Sometimes, they intentionally create their own internal regulatory bodies.   In all cases, such regulatory authorities *are* group agents  (and organizations.)

**Comment by elf-pavlik** [comment]
Thank you @fosterlynn your your in-depth response. I will limit my answer to just few lines selected from it

> Recently the Mutual Aid Network and FairCoop met to discuss ways they might collaborate economically. This was a meeting of peer networks exploring building a larger network connection.

I don't see it as 'meeting of peer networks', in practice just couple of people met who represented two organizations.

> Networks are a kind of group, no?

I don't think having both Group and Network makes much sense, possibly we may just have Organization which may represent both. Do you consider all networks as agents - having agency as network?

> Although freeform loosely held groups are totally valid too for other kinds of needs - I have really enjoyed the experience of ValueFlows as a loose global network.

I still don't consider VF as instance of *foaf:Agent*, more a *doap:Project* which some agents *maintain*, some *contribute* to and other just *follow*. R&D process which should output some knowledge resources.
I also think calling it  'global network' gives an example of overloading term Network. If we take network of all the agents (the whole social graph) we can select various subnets from it, for example "all agents that contributed to VF project". Some of them will not have any agent <-> agent relationships, some will have something like *rel:collaboratesWith*, some will have *org:memberOf* relationship the same organization, like you and @bhaugen to http://mikorizal.org/ But those subnets would not imply having agency as such. All the instances of foaf:Person and org:Organization would have agency.

**Comment by fosterlynn** [comment]
>> Recently the Mutual Aid Network and FairCoop met to discuss ways they might collaborate economically. This was a meeting of peer networks exploring building a larger network connection.

>I don't see it as 'meeting of peer networks', in practice just couple of people met who represented two organizations.

Well, there were a few core people from the MAN.  Then in the next FairCoop assembly, it was reported on and discussed how and if they wanted to relate.  And of course groups or organizations or networks don't have their own mouths, it has to be people representing them.

>Do you consider all networks as agents - having agency as network?

No, I don't think all networks are agents.

>All the instances of foaf:Person and org:Organization would have agency.

Agreed.  I'm not worried about our disagreement on VF, it is more a matter of making sure that groups / organizations can define themselves to have agency if they want.

>I don't think having both Group and Network makes much sense, possibly we may just have Organization which may represent both.

Maybe, thinking about it.  I don't want to eliminate looser groups or networks that do in fact consider themselves to have agency but may not want to think of themselves as formally as Organization.  So, foaf and org vocabs both have Person, Group, Organization.  

Schema does not have Group.  Their definition of Organization: "An organization such as a school, NGO, corporation, club, etc."  They also say "More specific Types:  Airline, Corporation, EducationalOrganization,   GovernmentOrganization, LocalBusiness, MedicalOrganization, NGO, PerformingGroup,    SportsOrganization.  More specific Types available in extensions:  WorkersUnion."  It sounds to me like they don't have Group because it is outside of their more corporate/ marketing focus, not because they think that Organization covers more loosely constructed groups or networks.  What do you think @elf-pavlik ?

**Comment by elf-pavlik** [comment]
> I don't want to eliminate looser groups or networks that do in fact consider themselves to have agency but may not want to think of themselves as formally as Organization.

Organization doesn't require anything formal other than creating an online record representing an instance of Organization. When it comes to legal systems currently in mainstream, they differ a lot in different parts of the world and vocab shouldn't in any way depend on any of those legal systems, otherwise we can't consider it universal.

Currently for VF we only need Agent (so it has agency) and way to distinguish between a Person and Non-Person agents, mostly because only a Person can *work*. Organization seems appropriate to represent Non-Person agents, and I don't think we need anything more then that for VF at least at its current stage.

I think we should resolve it in #182 and here clarify this 'Networks of Networks' or just 'The Worldwide Network' aspect. Just as we consider a Group in which other Groups participate as a Group, we can consider a Network in which other Networks participate as Network. I'll like to make it clear that what documentation currently calls 'Networks of Networks' pretty much means **a broader Network** where we can also distinguish **narrower Networks**, or **SuperNetwork** where we can distinguish **SubNetworks**. But 'Network of Networks' still stays a Network and not some 'higher level concept'.

**Comment by bhaugen** [comment]
We totally agree that a network of networks is also a network. That's basic.

We are also, of course, all enmeshed in the global capitalist networks of networks.

**Comment by fosterlynn** [comment]
>Organization doesn't require anything formal other than creating an online record representing an instance of Organization. When it comes to legal systems currently in mainstream, they differ a lot in different parts of the world and vocab shouldn't in any way depend on any of those legal systems, otherwise we can't consider it universal.

Do you consider that some networks are an Organization?  Do you consider that all networks that consider themselves to have agency as a network are Organizations?  I have the impression from the tons of discussion we had early on in the VF project that there are lots of people who resonate with the term Group because of relative lack of formality as the terms are usually understood in English - and would not think that Organization properly represents them.

>We totally agree that a network of networks is also a network. That's basic.

@elf-pavlik do you want to take a try at the working in the doc so that this is made more clear?  If not, I'll give it a try - but later, we're off now.

**Comment by ahdinosaur** [comment]
i prefer network-of-networks over the worldwide network with subnets, as to me the former promotes bottom-up organizing and the latter promotes top-down organizing.

**Comment by gcassel** [comment]
>i prefer network-of-networks over the worldwide network with subnets, as to me the former promotes bottom-up organizing and the latter promotes top-down organizing.

Mostly agree.  "Sub" often seems to imply "subordinate" .  By contrast, one could say that the worldwide network of (*potential*, usually *indirect*) connections is subsidiary to all of the (*actually* and *repeatedly*) used networks.

I personally find the term "Internet" quite neutral & acceptable as a description of the worldwide network of potential connections.   (without referring to other networks as "subnets" of the Internet.)   Do others dislike "Internet" or its perceived cultural baggage?

**Comment by bhaugen** [comment]
"Internet" will just invite confusion. I've enjoyed the various conversations comparing social networks (which is a term that everybody seems to understand) with economic networks, which seem to be understandable once people think about it. And then network of networks could be either or both.

**Comment by bshambaugh** [comment]
I just wanted to point out that my non-domain expert friend thought that
the semantic web was something that came about in the early 2000s that died
to difficulty of expressing meaning across domains and  the necessity of
human input. Also he thought that most people, would be overwhelmed by
graphs. He pointed out that these kind of people are not stupid (they just
see things a different way). He thought 3d graphs were cool. He also
suggested I make videos to excite people who might be interested in the
semantic web or linked data.

At any level, I'm sure value networks will be confusing. I'm often turned
down to speak with event with a certain programming group. Maybe it is
because I may not be an expert, or maybe it is because there may not be an
interest. Although the same group does seem to like graphs in LodLive and
thought I was respectable b/c of that (a linked data browser). I am thought
of as academic, yet some of my work as of late is thought of as beyond
beginner, and too complex to present at a beginner group. The average dev
seems to be into things like React, Ember, and Angular (Not bad stuff at
all). RDF is deprecated on Mozilla Dev Network as far as I can remember.  I
hope this helps in some way.

-Brent Shambaugh

GitHub: https://github.com/bshambaugh
Website: http://bshambaugh.org/
LinkedIN: https://www.linkedin.com/in/brent-shambaugh-9b91259
Skype: brent.shambaugh
Twitter: https://twitter.com/Brent_Shambaugh

**Comment by bshambaugh** [comment]
Oh, the same friend thought that Google did not need the semantic web
because the links people provided between pages was good enough

-Brent Shambaugh

GitHub: https://github.com/bshambaugh
Website: http://bshambaugh.org/
LinkedIN: https://www.linkedin.com/in/brent-shambaugh-9b91259
Skype: brent.shambaugh
Twitter: https://twitter.com/Brent_Shambaugh

**Comment by bshambaugh** [comment]
I guess the most important thing is to have something people can use easily?

-Brent Shambaugh

GitHub: https://github.com/bshambaugh
Website: http://bshambaugh.org/
LinkedIN: https://www.linkedin.com/in/brent-shambaugh-9b91259
Skype: brent.shambaugh
Twitter: https://twitter.com/Brent_Shambaugh

**Comment by bhaugen** [comment]
Re networks of networks: I think we need to look at how this stuff is now happening in real life. 

Fair Coop, Sensorica, GoPacifia, and the Mutual Aid Networks are all separate networks, and they are also  communicating and collaborating in several ways. Each of those netwoks has its own internal governance, rules, and customs. Three of them (I don't know about GoPacifia) contains other networks that are either contained or intersect in the networks I mentions. For example, Dezentrale is a separate network that is also a member of Freedom Coop, which is a network that was initiated by Fair Coop. Likewise the Mutual Aid Networks contain several members in different geographical communities. The Madison WI MAN intersects with a worker coop network. Etc.

When a couple of people from the Mutual Aid Network and Fair Coop met, they were individuals, to be sure, but they were also representing their different networks, as we saw very clearly in the Fair Coop context when people in a Fair Coop assembly were suspicious that the Mutual Aid Networks did not agree with the political goals of Fair Coop, and until those suspicious were allayed, did not want Fair Coop to associate with them. As the conversation progressed, consensus was reached that the two networks had enough agreement on principles and values that they could explore collaboration.

Value Flows is also a network, where we have members who meet mostly as individuals, but are also members of other networks: Enspiral, Sensorica, Fair Coop, Mutual Aid Networks, Vientos, etc etc. 

Value Flows has taken inputs (resource flows in the form of concepts) from at least Sensorica (NRP) and Enspiral (Open Apps), as well as contributions from people who learned how to make those contributions via their previous efforts in those networks.

Whether the Value Flows outputs will be used by those other networks remains to be seen, but if and when it does. those will be (to some extent) reciprocal resource flows.

So the network of networks is connected at the boundaries of each network, by individuals and groups from one network collaborating with another, and via resource flows, and also by some individuals who belong to more than one network. But each of the networks I have named retains its own identity and practices as a separate network, too. Sensorica does not work the same way as Enspiral which does not work the same way as Fair Coop which does not work the same way as the Mutual Aid Networks.

**Comment by fosterlynn** [comment]
>It should be noted that most networks of autonomous participants are at least partially subject to one or more regulatory bodies. Sometimes they don't even realize it. Sometimes, they intentionally create their own internal regulatory bodies. In all cases, such regulatory authorities are group agents (and organizations). However, those organizations aren't identical to the networks-- not even on a formal level!-- except arguably in cases where all network participants have explicitly accepted the formal authority of regulators. (Which frequently does happen via "Terms of Service", etcetera.)

It is interesting you look at the organizations created by networks as possibly separate from the networks themselves.  Not sure I get that, except that the term organization has some implication of a fairly formally described definition.

I think from all this discussion, we have to make sure we distinguish between networks or groups who are economic agents and those who aren't.  Seems they only are agents if they have agreed on some level to identify and act as a group.  I'm sure there are gray areas.  I think it would be good to try to clarify the different positions in our documentation.  But at the same time, I think that we will need to provide all the options and let people decide for themselves.

Today I'll spend some time trying to upgrade our proposed release doc to accommodate all as much as possible, and let you all tear it apart...  :)

**Comment by fosterlynn** [comment]
>I just wanted to point out that my non-domain expert friend thought that the semantic web was something that came about in the early 2000s that died to difficulty of expressing meaning across domains and the necessity of human input. 

thanks @bshambaugh 

I'm not sure where the semantic web, and linked open data in particular, will go (I am very non-expert, as @elf-pavlik will testify :blush: ).  But it for sure still has life, and we have committed to go that route as our principle path.  Some of us also have tried to make sure that VF can support non LOD solutions too, like the one @ahdinosaur is working on.  I personally am committed that the vocabulary itself should be able to be represented in whatever ways things develop, if at all possible.  I'm pretty sure there will be lots of different experimentation going on technically.

> At any level, I'm sure value networks will be confusing.

Yeah.  I hope our doc helps, and hope that anyone who finds it confusing, and has some time, will help us make it better! :smile:   But also, several of us are participating in software experiments that try at least in part to use VF, and that is another way to disseminate, get it right, and get it documented.

**Comment by gcassel** [comment]
>It is interesting you look at the organizations created by networks as possibly separate from the networks themselves.

I've lived through this *many* times @fosterlynn :  (1) there's an informal network of peers and  (2) *some* of those people create an organization to regulate/run that network, without the consent of the other participants.

In other words, it's not "the network" which creates the organization.  It's a subgroup.  It's often a self-assigned subgroup.   

As I mentioned previously, however, one could consider the whole network to be an organization if all of the participants sign "Terms of Agreement" which explicitly recognize a formal authority.  However,I prefer to entirely avoid that equation of network=formal organization.    (Y'know, even if there's a network where everyone must currently sign Terms of Agreement, they could create participation-types which have no such formal association.  Also, I think that a network technically includes viewers/ bystanders who are able to read, but not to write to any channels.)

>I think from all this discussion, we have to make sure we distinguish between networks or groups who are economic agents and those who aren't. Seems they only are agents if they have agreed on some level to identify and act as a group.

That's precisely how I personally use the term "group agent".   
It may be best ultimately to use the less concise term "collective agent" for two reasons:   (1)  to emphasize the (arguably Borg-like, lol) delegation of personal agency to a collective entity,  and  (2) to reduce confusion with the very widespread, broad & vague use of the term "group".

**Comment by fosterlynn** [comment]
>I believe that the term "group agent" should be reserved for groups which hold (often small, strict) domains of formal authority which are explicitly accepted by the members of those groups.

I am hoping this also will provide some input there. http://www.jamesodell.com/Odell-AOSE04.pdf

**Comment by fosterlynn** [comment]
>That's precisely how I personally use the term "group agent".
>It may be best ultimately to use the less concise term "collective agent" for two reasons: (1) to emphasize the (arguably Borg-like, lol) delegation of personal agency to a collective entity, and (2) to reduce confusion with the very widespread, broad & vague use of the term "group".

Hmmmm, I might like GroupAgent.  Although I'm not sure enough to go away from using foaf?  And in some ways the vagueness is OK, so people can do what they want within some general understanding. Thinking.

Although neither GroupAgent nor CollectiveAgent encompass Organization, which does not need to include more than one person.

**Comment by fosterlynn** [comment]
>I've lived through this many times @fosterlynn : (1) there's an informal network of peers and (2) some of those people create an organization to regulate/run that network, without the consent of the other participants.

Yes there are lots of un-democratic dynamics in many groups and networks, since none of us have shed all the bad habits and unobjective views of ourselves internalized by living in this world, whether inflated or deflated.  It will be a process not accomplished in one generation.  It is a bit tricky to think about what is the role of a simple vocabulary in that....

**Comment by djodjoni** [comment]
@bshambaugh 
(a little late :)
> I just wanted to point out that my non-domain expert friend thought that
the semantic web was something that came about in the early 2000s that died
to difficulty of expressing meaning across domains and  the necessity of
human input. 

It is indeed difficult but actually happening as it apparently has value :)
btw check this talk :)
https://www.youtube.com/watch?v=oKiXpO2rbJM

> Oh, the same friend thought that Google did not need the semantic web
because the links people provided between pages was good enough

Well it is apparently not good enough as Google [ask them](https://developers.google.com/search/docs/guides/) to tag those links and Google wouldn't invest in Schema.org, Freebase, Knowledge Graph etc.

But I completely agree whatever there is, in order to be used, it has to be easy and as simple as possible, but not more :)

**Comment by elf-pavlik** [comment]
>  But at the same time, I think that we will need to provide all the options and let people decide for themselves.

Working in Open World Assumption allows people to create in independent or coordinated way all the options they may want to choose. In ValueFlows we should only focus what the vocab itself requires to clearly define meaning of used concepts. Since not everything that people may want to call a 'Network' has agency, we can't define it as subclass of Agent. When it comes to precise terms defined in vocab I think we should continue in https://github.com/valueflows/valueflows/issues/182#issuecomment-287633133

 > It should be noted that most networks of autonomous participants are at least partially subject to one or more regulatory bodies. Sometimes they don't even realize it. Sometimes, they intentionally create their own internal regulatory bodies. In all cases, such regulatory authorities are group agents (and organizations).

That makes sense to me, close to none of the agents that produce, process, distribute and consume food distributed by Open Food Network, engages in any way in https://community.openfoodnetwork.org/ Most of those agents only interact with their local OFN Organization (which runs the local instance) and they relate to that organization as 'service provider'. Each local OFN Organization acts as distinct agent from all the agents who use its service, and what one may want to call a 'Network' has no agency itself.

**Comment by fosterlynn** [comment]
>Most of those agents only interact with their local OFN Organization (which runs the local instance) and they relate to that organization as 'service provider'. Each local OFN Organization acts as distinct agent from all the agents who use its service, and what one may want to call a 'Network' has no agency itself.

In terms of using this as an example then (and I'm good dropping Network from our vocab), do the independent agents that interact with the local OFN as a service provider consider themselves part of that local OFN?  Is there any agreement involved, or implied by using OFN and how it works?

**Comment by elf-pavlik** [comment]
Independent agents (producing and distributing food) agree to Terms of Service used by local OFN organization but don't automatically become member of that organization. At the same time we can consider that OFN organization also acting as hub which defines something one can consider a network - all the peers connected to that hub. At the same time efforts like http://datafoodconsortium.org/ aims at enabling all those peers (independent agents) to connect to any number of hubs. So the networks start merging not by agreements between organizations running those hubs but by independent peers connecting to as many hubs as they like.

**Comment by bhaugen** [comment]
The food networks we worked with aggregated and distributed food. Like http://www.fifthseasoncoop.com/

**Comment by elf-pavlik** [comment]
I think http://www.fifthseasoncoop.com/ can stay represented as Organization (coop) http://www.fifthseasoncoop.com/join-us/
At the same time it seems that any of 'member' organizations can also act independently of the coop and possibly also join other coops. I still don't see reason to call some organizations 'Networks' and other organizations 'Groups', I don't think anyone even presented clear criteria on how to classify any organization as either Group or Network. 

BTW we had chat yesterday with Devin about http://coopdata.org/standards/ and he mentioned meeting recently with Tibi in Montreal ...

**Comment by fosterlynn** [comment]
>So the networks start merging not by agreements between organizations running those hubs but by independent peers connecting to as many hubs as they like.

So sounds like the local hubs are agents; the connections through peers belonging to more than one hub do not make more agents.

>I still don't see reason to call some organizations 'Networks' and other organizations 'Groups', I don't think anyone even presented clear criteria on how to classify any organization as either Group or Network.

That's fine with me.  Let's keep Group, or GroupAgent.

**Comment by gcassel** [comment]
>Independent agents (producing and distributing food) agree to Terms of Service used by local OFN organization but don't automatically become member of that organization.

I may seem fussy with words here @elf-pavlik , but I suggest that :   by agreeing to Terms of Service, one formally becomes a *participant* in an organization, but not necessarily a *member*.    Often, a "member" is defined as a type of participant with special rights & responsibilities.

**Comment by gcassel** [comment]
>>I believe that the term "group agent" should be reserved for groups which hold (often small, strict) domains of formal authority which are explicitly accepted by the members of those groups.

>I am hoping this also will provide some input there. http://www.jamesodell.com/Odell-AOSE04.pdf

Reading the abstract & speedreading the rest, it all seems sound & mostly equivalent to my models.  For instance, I essentially agree with this bit:
>An Agentified Group possesses all the features that any agent might possess. For example, it can send and receive messages directly and take on roles. Such a group is an agent in its own right, and therefore is a subclass not only of Group but also of Agent. 

"Agentified group" seems almost identical to what I call "group agent" or "collective agent".  However, I don't know (speedreading) if the authors explain here or elsewhere how a group of people "send and receive messages" as a collective.  

Of course, many existing groups are quick to issue statements "in the name of the group" when those statements are, often privately or secretly, composed by individuals who've been assigned with (or often, quietly *assumed*) executive authority. 

I have my own strict views on consent-based collective statements, per this bit in [Agreement-Based Organization](https://docs.google.com/document/d/1c_xWEIay-2jyJ3Rqb6OgTxoZBJfjNW4d6w6ukXyeJk4/edit?usp=sharing):

>Consistently consent-based agreements can be created, and amended, in two ways:

>1. By adding (ink or digital) eligible signatures to written proposals.  Each eligible signatory becomes a member of that agreement.  
>2. By directly attaching an agreement to an existing agreement or agreement-based group.  This requires agree/abstain/disagree/block consensus process or an equivalent technique, establishing the direct consent of the existing agreement’s members.

**Comment by gcassel** [comment]
>Yes there are lots of un-democratic dynamics in many groups and networks, since none of us have shed all the bad habits and unobjective views of ourselves internalized by living in this world, whether inflated or deflated. It will be a process not accomplished in one generation. It is a bit tricky to think about what is the role of a simple vocabulary in that....

I think that a vocabulary can enable all peers to call a spade a spade, so to speak-- or at least, to accuse spade-like entities of being spades.  (And, *be held accountable* among peers for such accusations.)  

I (rather) peacefully accept the fact that people will often knowingly surrender their personal agency to others.  By contrast, I actively fight against confusion, intentional obfuscation and deception.   A highly descriptive vocabulary can reduce their likelihood.

**Comment by gcassel** [comment]
I've contributed to diffusing this discussion; please feel encouraged to refocus or resolve @elf-pavlik

**Comment by fosterlynn** [comment]
>by agreeing to Terms of Service, one formally becomes a participant in an organization, but not necessarily a member. Often, a "member" is defined as a type of participant with special rights & responsibilities.

I think that is a useful distinction.  Perhaps a participant could even be less formal, an agent who by way of some events is in fact interacting with a network, but is not a member, won't have any relationship record at all?  (And perhaps the network doesn't even have members.)

**Comment by gcassel** [comment]
>Perhaps a participant could even be less formal, an agent who by way of some events is in fact interacting with a network, but is not a member, won't have any relationship record at all? 

I've come to use the term "participant" frequently @fosterlynn but I don't think I've ever defined it directly.  "User" is a nearly synonymous (and typical) term.  I think that "user" has some unfortunate connotations.  

I think that "participant" should indeed indicate anyone who interacts with (or "takes part in") a network.   With online networks, this can include anyone who's capable of receiving & sending (or reading/writing) signals to the network.  For instance, public networks can be "read" by anyone, but usually do have restricted "writing" abilities.

Participants are often *quite* informally involved:  for instance, people who occasionally browse a facebook group or a Twitter account's "wall".   However, *types* of participant  (including "member") can of course be formally defined by creating a set of rights & responsibilities per type.   Users/ participants are often expected to accept Terms of Service or User Agreements, etcetera, which describe those formal rights & responsibilities.

**Comment by elf-pavlik** [comment]
> I think that is a useful distinction. Perhaps a participant could even be less formal, an agent who by way of some events is in fact interacting with a network, but is not a member, won't have any relationship record at all? (And perhaps the network doesn't even have members.)

If some organization provides services to some agent, they could even express it as some kind of 'customer' relationship, or 'beneficiary' or however we want to call an agent that benefits from operations of another agent. So we don't talk just about having some/any relationship or not, concept of membership in most vocabs relies on clearly defined relation that conveys meaning 'membership'.

We had discussions around that already in https://github.com/valueflows/agent/issues/51#issuecomment-150240833 and I don't expect we will resolve it any soon. Once again I propose to resolve our current requirement of Person and Non-Person agents in #182 and here focus on Networks of Networks and Networks of (Networks of Networks) and Networks of (Networks of (Networks of Networks)) ... i guess this [Matryoshka doll](https://en.wikipedia.org/wiki/Matryoshka_doll) thing comes as an input from Sensorica new ventures :wink:

**Comment by fosterlynn** [comment]
>i guess this Matryoshka doll thing comes as an input from Sensorica new ventures, just AFAIK those dolls don't support multi parent hierarchies :wink:

haha, I wonder if that is where they got the name :)

BTW, I posted a PR, looking forward to feedback!

**Comment by fosterlynn** [comment]
Closing, assuming the text in the doc works for people.  Please reopen if you disagree.
