### ISSUE TITLE
Link Dumps 2018

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#269]
Really annoying blog with really annoying nag popups, but good content for understanding shipping documents.

https://shippingandfreightresource.com/when-does-a-bill-of-lading-become-a-contract-of-carriage/

**Comment by bhaugen** [comment]
[COAR Controlled Vocabularies](http://aims.fao.org/fr/activity/blog/use-coar-controlled-vocabularies-enhance-interoperability-across-repositories-and)

With [Resource Types](http://vocabularies.coar-repositories.org/documentation/resource_types/)!

**Comment by gcassel** [comment]
>COAR Controlled Vocabularies

>With Resource Types!

Very interesting; thanks for sharing.   The work is solid, extensive, and open sourced.

There are some quirky points in a quick viewing..  For example, their resource types are (implicitly) all *media resource types*, due to their focus on "research resources".   Thus, they don't (directly) cover representations of physical or social resources, as Value Flows (and Modular Organization Terminology) attempt to.     Also, it'll be interesting to see if they do or don't formally relate the concept of *edition* to the concept of *version* (as I do.)   

With that said, it's a valuable resource that could be plugged into or adapted into open works moving forward.   I've saved the links for my Community Resource Description Framework prototypes-- thanks for sharing!

**Comment by bhaugen** [comment]
The category theory posse has recently features two different universal programming languages with blockchains. I ask here, are they composable?
https://johncarlosbaez.wordpress.com/2018/02/04/pyrofex/#comment-103189

I think if you know category theory, that is somewhere between ironic and hilarious...but then I don't really know category theory yet.

**Comment by bhaugen** [comment]
[open citations](http://www.ch.imperial.ac.uk/rzepa/blog/?p=19392)

**Comment by bhaugen** [comment]
[Open Digital Rights Language](https://www.w3.org/TR/odrl-model/)

Quick reconnoiter: 
* Their Asset is vf:EconomicResource
* Their Party is foaf:Agent

More to come...and please help map.

**Comment by bhaugen** [comment]
[Commitment networks!](https://johncarlosbaez.wordpress.com/2018/02/19/complex-adaptive-systems-part-7/)

> It has four nodes, which represent agents... The edges between these notes describe relationships between these agents. Some of these relationships are ‘commitments’.

**Comment by gcassel** [comment]
>Some of these relationships are ‘commitments’.

They also refer to relationships via communications channels.  A communication channel is a resource.   Lately I'm trying to finesse some ideas (and hopefully practices) regarding agents' ability to commit to the governance of resources (including channels!) as peer-members with one vote each in consent-based constitutional decisions.    

I hope to follow up later with relevant shared media items.

**Comment by bhaugen** [comment]
https://aos.github.io/2018/02/24/understanding-dijkstras-algorithm/

Useful for traversing flow graphs, especially for transportation. See also https://github.com/valueflows/django-vocabulator/issues/7

**Comment by gcassel** [comment]
Haven't read this yet but should be relevant  @bhaugen and @fosterlynn    :  https://primer.commonstransition.org/4-more/5-elements/case-studies/case-study-sensorica

**Comment by bhaugen** [comment]
https://blog.wikimedia.org.uk/2018/02/structured-data-on-commons-is-the-most-important-development-in-wikimedias-usability/

> Wikimedia Commons is one of the most important sources of Creative Commons licensed media online. But it has a huge problem: it’s a total mess.

One of the biggest complaints about Commons which discourages people from using it is that it’s incredibly hard to find what you’re looking for. People upload files and fill out some information about their content, but not in a particularly systematic or structured way, with minimal automated assistance.

This means that when you try to search for something on Commons, you’ll be presented with a huge array of files with minimal relevance to your search. You can’t even really search for media by date. Which date would you be searching for anyway? The date the media was created, the date it was modified or the date it was uploaded? Without systematic organisation of media on Commons, it will continue to represent a disorderly and overgrown garden that desperately needs work to give it some order.

> This is where the [Structured Data on Commons (SDoC) project](https://commons.wikimedia.org/wiki/Commons:Structured_data) comes in.

**Comment by bhaugen** [comment]
![twelf](https://user-images.githubusercontent.com/117439/38334734-ce9a0a4e-3821-11e8-973f-3f08a540e7db.png)

http://twelf.org/wiki/Main_Page
> Twelf is a language used to specify, implement, and prove properties of deductive systems such as programming languages and logics.

**Comment by gcassel** [comment]
FYI, my prototype **[Inclusive Design Cycle](https://docs.google.com/document/d/1E5V8LggadbbAaJw9tK_OT22VyciO4OE9ml1fiXYyfmk/edit?usp=sharing)** has been slowly developing.  It currently feels substantial and stable enough to share as an informal RFC here in Value Flows, and also as an informal FYI publicly.   

As the document's intro states, *Inclusive Design Cycle* functions as the sequential creative process in a **Conversation for Action** to develop and pursue any specific goal within the [Resource Development and Support System](https://docs.google.com/drawings/d/1YG-C8xxFFzN3o8fOOrQbAKlBoKf-ZHvhBKe6i7a8m7w/edit?usp=sharing) model.  Inclusive Design also functions as a suggested model for developing inclusive proposals in [Agreement-Based Governance](https://docs.google.com/document/d/1c_xWEIay-2jyJ3Rqb6OgTxoZBJfjNW4d6w6ukXyeJk4/edit?usp=sharing).

BTW note that the linked Resource Development and Support System model does *not* yet illustrate recent revisions to the Inclusive Design Cycle.  Revising that RDSS visual diagram is laborious, so I'll update it after Inclusive Design Cycle feels more stable and temporarily "finished".

I realize of course that my personal design of *Conversation for Action*-- with interlocked *Inclusive Dialogue Cycle* and *Inclusive Design Cycle*-- is quite different from previous Conversation for Action models which focus on *buyer* and *seller*; i.e. exchanges between potentially "neutral" parties who may require contracts.    Plus I'm more focused on Inclusive Design Cycle *and* the broader *RDSS* model than I am on *Conversation for Action* per se.  Frankly I'm quite overworked, so I don't expect to directly coordinate/integrate my model with previous Conversation for Action models unless that seems very important for VF.    Of course, I would carefully consider any ideas, suggestions or requests!

Also note, I'm sharing this in Link Dumps because it doesn't seem very relevant to other active Issues; however, I'd support efforts to coordinate this with anything else such as https://github.com/valueflows/valueflows/issues/266 .

**Comment by bhaugen** [comment]
@gcassel you been busy on this! A lot to look at, and it looks like you are still actively changing it. 

I think it would be good to start a new issue thread to discuss this. I may also comment on the document itself.

One comment here: 
> previous Conversation for Action models which focus on buyer and seller;

Conversation for Action originally came from Stafford Beer and Fernando Flores work on Cybersyn in the Allende government in Chile, which of course was aborted by a US-financed coup.
https://en.wikipedia.org/wiki/Stafford_Beer#Cybersyn

It was not originally about buyers and sellers, but about agreements between production and distribution organizations in an economy that was trying to evolve to some kind of mutual-coordination (not command-and-control) socialism. 

Got reformulated and formalized for buyers and sellers when Flores and Terry Winograd started a software company in the US after Flores got out of prison in Chile.

**Comment by gcassel** [comment]
Thanks @bhaugen for clarifying some of the history of Conversation for Action!   I may have read some of that before, but I have a lousy memory.

Per your feedback, I guess I'll turn my previous comment here into a new issue thread.

**Comment by bhaugen** [comment]
https://dock.io/how-it-works
> dock.io is a decentralized data exchange protocol that lets people connect their profiles, reputations and experiences across the web with privacy and security.

> The Consequences of Closed Networks
A person’s profile and information lives on hundreds of apps which are all closed networks and centralized sources. These apps control data at their will, while users and other companies are left with limited opportunities.

> Capable of Powering All Consumer Apps
The dock.io protocol is low in the tech stack making it capable of powering data for every consumer app in the world.

**Comment by bhaugen** [comment]
Universal Viewer:
http://universalviewer.io/
https://docs.google.com/presentation/d/1YmBvOZhokhkpn_dHKzJR5gH4W7qV0ncVY_fjzaPhyws/edit
> IIIF Presentation is like a markup document for digital objects (books, manuscripts, radio plays, TV shows, terracotta jugs), except it uses 
{json-ld} instead of \<tags\>. We call them “IIIF Manifests”.

**Comment by bhaugen** [comment]
http://www.compositionality-journal.org/
> Compositionality describes and quantifies how complex things can be assembled out of simpler parts. Compositionality, the journal, is a new diamond open-access journal for research using compositional ideas, most notably of a category-theoretic origin, in any discipline. Topics may concern foundational structures, an organizing principle, or a powerful tool. Example areas include but are not limited to: computation, logic, physics, chemistry, engineering, linguistics, and cognition.

> The first issue of the journal is slated for publication in (northern) summer 2018.

> In the meantime, community consultation is taking place [on reddit](https://www.reddit.com/r/compositionality/). Please join the discussion!

**Comment by elf-pavlik** [comment]
http://help.zenodo.org/#versioning
```txt
What is DOI versioning?

DOI versioning allows you to:

    edit/update the record’s files after they have been published.
    cite a specific version of a record.
    cite all of versions of a record.

How does DOI versioning work?

When you publish an upload on Zenodo for the first time, we register two DOIs:

    a DOI representing the specific version of your record.
    a DOI representing all of the versions of your record.

Afterwards, we register a DOI for every new version of your upload.

...
```

Something like above might come helpful with *cite* action.

**Comment by almereyda** [comment]
https://w3c-ccg.github.io/did-spec/

> #### Decentralized Identifier (DID)
>    A globally unique identifier that does not require a centralized registration authority because it is registered with distributed ledger technology or other form of decentralized network. The generic format of a DID is defined in this specification. A specific DID scheme is defined in a DID method specification.

**Comment by fosterlynn** [comment]
>Decentralized Identifier (DID)

Thanks @almereyda , very timely.  Are you thinking of going in that direction in any of your work?

**Comment by bhaugen** [comment]
Open letter to the authors of http://www.mdpi.com/1911-8074/11/2/26/htm
(also sent via email)

## Thanks for the ValueFlows citation in your excellent paper...

...but you misunderstood a couple of factors that would make your article stronger.

1. ValueFlows is the collective creation of a floating unorganized group of people, as you can see here: https://github.com/orgs/valueflows/people

And at least one key contributor is missing from that list. And a lot of the content came from Sensorica.

2. It's not at all academic, although we do have an academic mentor of sorts, Bill McCarthy of Michigan State U. I don't even have a college degree. And am definitely not the main author.

This is a new day, and a new type of organization. so a more accurate citation might be the ValueFlows unorganization, or something like that.

Beyond that, though, I really enjoyed the paper. Best article I've seen so far on what is happening in this value-network space from a big company.

Thanks,
Bob Haugen

**Comment by daniellestanko** [comment]
I'm glad you enjoyed the article, and I'd like to use your comments as an opportunity to learn more.

1) We may have different definitions of an organization (my definition would be a group of people coming together around a common purpose, whether or not there it is a registered legal entity. It's an organized group), and in the article we reference ValueFlows with respect to Open Value Accounting, not so much a defined organizational entity. 

Could you elaborate on why you're calling it an unorganized group? Is this related to the legal connotation of "organization" or around the idea that ValueFlows has very loose ways of organizing, and is in a sense, unorganized (chaotic, flows)?

A lot of our content came from Sensorica because we were talking with Tibi, the founder, and therefore had better information to rely on from those conversations. However, I would be open and interested in learning about other open network projects going on. If you or any others would like to talk, propose a time. The more I understand, the more I can work to help open networks to proliferate. I am doing my best to understand new and better ways that people can organize so that society stops self destruction for the sake of money.

2) I was not the author of the specific wording that references it as academic work, but believe that was written so because of its foundations on REA. I will pass the comment along to Andreas Freund, who was not part of the email thread.

**Comment by bhaugen** [comment]
[effective standards work](https://infrequently.org/2018/06/effective-standards-work-part-2-threading-the-needle/) from Alex Russell, who has worked on a lot of standards committees.

I think we are doing a lot of what he advises.

I had the good luck to work with Alex a bit when he and I were working on JotSpot before Google bought and killed it. He was a delight to work with. Apparently he stuck with Google after the acquisition. I was just a consultant, didn't get anything from the buyout except that my consulting platform was dead...

**Comment by almereyda** [comment]
Happened to run into http://ontoology.linkeddata.es/ on Twitter. Did we use or know this already?

**Comment by fosterlynn** [comment]
>Happened to run into http://ontoology.linkeddata.es/ on Twitter. Did we use or know this already?

Haven't run into it, looks interesting, will try it out! Thanks!

**Comment by almereyda** [comment]
Who else is thinking of Portable Linked Profiles here?

> The Data Transfer Project makes it easy for people to transfer their data between online service providers. We are establishing a common framework, including data models and protocols, to enable direct transfer of data both into and out of participating online service providers.
>
> https://github.com/google/data-transfer-project
>
> https://datatransferproject.dev/

**Comment by elf-pavlik** [comment]
Very late notice but in less than 3 hours this virtual summit will happen https://businessofblockchain.com/web/virtual-summits/blockchain-id some of the participants:

* Christopher Allen (Blockchain Commons)
* Manu Sporny (DigitalBazaar and Veres.One)
* Drummond Reed (Sovrin Foundation)
* Rouven Heck (Consensys)

**Comment by bhaugen** [comment]
@almereyda 
> Who else is thinking of Portable Linked Profiles here?

It's an aspect of the agent-centric architecture that @fosterlynn and I and others have been working on.

Here's an  [intro](https://www.loomio.org/d/3wDCtkoG/structuring-the-oae-around-agents) and [more notes](https://cryptpad.fr/pad/#/1/view/HCGmHSwjgSNEOONNPRLplA/CyJfwJFLO3RXcFysO0sGKmh4sGpiC4XRMVc5CE7Ozdw/).

We're thinking of ActivityPub as one possible implementation, where every agent would have their own activitypub instance, which might be self-hosted or hosted by a service. In the service case, agents would want to be able to move their AP to another service or to their own server.

Would that fit into the Data Transfer Protocol?

**Comment by almereyda** [comment]
dazinism just shared this to #ecobytes:matrix.allmende.io:

- [Past, present and future of an economic network](https://ivanminutillo.com/2018/09/04/past-present-future-of-an-economic-network)

**Comment by bhaugen** [comment]
Good article by @myriamboure of the [Data Food Consortium](https://github.com/valueflows/valueflows/issues/229) and Open Food Network:
http://blogfr.p2pfoundation.net/2018/09/17/les-communs-le-modele-de-lapres-capitalisme-liberal/

I read it using a translator so might have missed some of the nuances, so I won't quote anything here. But all of Myriam's work seems closely related to what we are doing here.

**Comment by myriamboure** [comment]
@bhaugen thanks for sharing :-) I actually translated the article: https://medium.com/@myriamboure/commons-the-model-of-post-liberal-capitalism-55375f052a22 if that can help. 
Probably we would need to talk more in the months to come. There are interesting things happening, especially on "peer based standardization" processes facilitated by commoners ecosystem. I'll come back to you. Cheers!

**Comment by fosterlynn** [comment]
@myriamboure thanks very much for the translation!  And really looking forward to talking more and finding out about "peer based standardization" - sounds very intriguing.....

**Comment by almereyda** [comment]
Friend `@vmx` was so friendly to share with me:

- https://mjg59.dreamwidth.org/51177.html

via https://twitter.com/vmx/status/1043655785883033600

**Comment by bhaugen** [comment]
I am currently pouring over Ian Grigg's work and writings: 
http://www.iang.org/papers/

Focusing on these for now: 
* https://nakamotoinstitute.org/financial-cryptography-in-7-layers/#selection-1335.99-1335.102
* https://nakamotoinstitute.org/the-ricardian-contract/
* https://chamapesa.com/

I'm posting this at least partly in case anybody wants to join me in some study and discussion.

**Comment by almereyda** [comment]
https://github.com/BEICOOP/BEICPBLChallenge/blob/master/Phase3/Stakeholders_Roles/Designer.md made me think of @nogo10's post in https://github.com/valueflows/valueflows/issues/284#issuecomment-433694923

**Comment by almereyda** [comment]
Closing in favour of #422 .
