### ISSUE TITLE
Budgets, estimates, forecasts, and plans

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#284]
This issue was prompted by some particular use cases, for example, [Ontology for a solidarity-based food system](https://lab.allmende.io/solidbase/solidbase/issues/12), which is trying to model budgets for [Solawis](https://solawi-marburg.de/inhalte/was-ist-solawi), which are an advanced form of [Community-Supported Agriculture](https://en.wikipedia.org/wiki/Community-supported_agriculture).

But other people have asked how to model budgets in REA, and also how to estimate equipment costs for agriculture.

I'm starting this as an issue, but if it gets good, might turn it into a wiki article or some other form of publication. And eventually one of the imagined [vf-apps](https://github.com/valueflows/vf-apps) and then maybe some code.

This will be discursive and probably recursive. I'll look at different practices of budgeting and forecasting I have known or seen, and hope others will join in, and we get something useful out of the discussion.

**Comment by bhaugen** [comment]
### Directions of planning

Budgets, estimates, and forecasts, are all forms of planning.  Planning can just be a SWAG (systematic wild-assed guess) or it could be calculated from some known information plus some guesswork.

Calculating from known information can be done in different directions, depending on what is known and what is the desired outcome.

Two forms of different directions:
* top-down vs bottom-up
* demand-driven vs supply-driven

By top-down vs bottom-up, I don't mean a hierachy of people, but a hierarchy of information, where top-down would start with summary or conceptual information and explore the details, and bottom-up would start with the most detailed information and aggregate to higher levels of summary and concept.

Whether planning is done top-down or bottom-up logically depends on whether the resource flows are driven by demands or supplies.

By demand-driven vs supply-driven, I mean what is a given factor vs what is variable and dependent on given factors. 

For example, in a product manufacturing environment, planning is often driven by the demands for a product, in terms of customer orders, either actual or forecasted.

In agriculture or some other cases, for example a paper mill, the supply of various crops (once they have been planted) or the web of paper coming off the mill is what is given. 

Usually there is some point in supply or demand driven scenarios where the demand and the supply meet. 

In supply-driven situations, the supplies are routed to different destinations at some point in the resource flow. In agriculture, that is at harvest time. In a paper mill, that is called the rewinder station: where the continuous web of paper coming off the mill gets slit and rewound on cores and made into reels of different widths and lengths. In both cases, goods are coming off of a supply line and going to various destinations and end uses.

In demand-driven situations, like manufacturing, the demands for end items need to be "exploded" into the detailed inputs and processes required to produce the demanded outputs.

**Comment by bhaugen** [comment]
### Focusing on Solawis and CSAs

I've seen or heard of two different models for community-supported or solidarity agriculture:
* The usual model of a CSA in the USA is a private farm that offers regular food deliveries (usually food boxes at pickup points) during the growing season to members, who are people who pay upfront for some time period, often a year, to receive the food deliveries.
* I have heard of Solawis in Europe where the community owns the farm, and in effect "hires" the farmer,, or to think of it differently, the farmer(s) is(are) a member(s) of the community who manage(s) the farm.

The US CSA is more like a capitalist venture where the farm does its own budgeting and figures out what membership fee they need for ongoing operations and then hopes to sell enough memberships to cover their needs for farming operations and their own lives.

In Solawis. I have heard of (but have not personally experienced) rounds of budgeting and offers of contributions using a more communal model, where if the offered contributions do not meet the budget needs, another round of budgeting and contributions begins, until the seasonal requirements are met.

[Ontology for a solidarity-based food system](https://lab.allmende.io/solidbase/solidbase/issues/12) appears to apply to the communal model.

**Comment by bhaugen** [comment]
### Focusing on manufacturing

The usual practice in the US and Europe is cycles of Master Production Scheduling (MPS) and Material Requirements Planning (MRP).
* https://en.wikipedia.org/wiki/Master_production_schedule
* https://en.wikipedia.org/wiki/Material_requirements_planning
* https://www.archerpoint.com/blog/Posts/difference-between-mrp-and-mps

[Demand forecasting](https://en.wikipedia.org/wiki/Demand_forecasting) is usually part of MPS.

But regardless of how derived, records of demand for end products (independent demands) are then "exploded" by MRP into dependent demands for components. In supply chain planning, the demands for components might be communicated to the suppliers of the components, where they would be independent demands for the supplier's planning cycle.

**Comment by bhaugen** [comment]
### What is a budget?
> An estimate of costs, revenues, and resources over a specified period, reflecting a reading of future financial conditions and goals.
One of the most important administrative tools, a budget serves also as a (1) plan of action for achieving quantified objectives, (2) standard for measuring performance, and (3) device for coping with foreseeable adverse situations.

Read more: http://www.businessdictionary.com/definition/budget.html

So a budget seems to require a plan ("an estimate of costs, revenues, and resources over a specified period"), as well as being a plan.

I'll assume we have an agent (person or organization) that will define a scope for a budget, and the specified period is the coming year. (MPS, described above, calls this a Planning Horizon."

To estimate cost, revenues, and resources, will require figuring out what that agent will be doing over the year.

In VF we usually talk about what an agent is doing as a Process, and the type of process they are doing as a Process Classification.  And the requirements for a Process are quantities of Resources of different Resource Classifications.

But the process-for-a-year is different from the process that starts and ends today.  The [Solidbase data structure](https://hack.allmende.io/solidbase_datastructure) calls the process-for-a-year "Activity". In [locecon](http://locecon.org/) we called them "Functions". But it's the same idea, of an aggregate Process Classification that has as its inputs and outputs quantities of Resource Classifications for an entire Planning Horizon.

For example: 
![Nova Scotia groundfish resource flows](http://locecon.org/site_media/images/groundfish_network.png)

So the costs, revenues, and resources in the budget will be computed from the inputs and outputs of the Activities, Functions, or Aggregate Resource Types for a Planning Horizon.

**Comment by gcassel** [comment]
This is a fundamentally important topic and I think you're approaching it effectively-- thanks!!   I have some related definitions in MOT such as *[budget](https://github.com/gcassel/Modular-Organizing-Terminology/blob/master/terms/budget.md), [assign](https://github.com/gcassel/Modular-Organizing-Terminology/blob/master/terms/assign.md), [allocate](https://github.com/gcassel/Modular-Organizing-Terminology/blob/master/terms/allocate.md)* but I doubt they'll be useful with your strict design imperatives.   Certainly feel free of course to adopt, adapt or discuss any elements in those definitions.

**Comment by bhaugen** [comment]
@gcassel what I really want from you is vocabulary for making agreements between agents. I'll ping you in gitter about that, maybe tomorrow when I have more time to think.

**Comment by nogo10** [comment]
Steve here: I'm somewhat familiar with budgeting as I have to often prepare class D and A estimates. Risk analysis usually accompanies these budgets to establish contingencies. 

For equipment purchases that's another matter: my understanding is that it can be ROI or debt financing analysis that could be 'embedded' in a value accounting framework as a cost in production.

**Comment by bhaugen** [comment]
@nogo10 thanks for commenting.
>  I'm somewhat familiar with budgeting as I have to often prepare class D and A estimates.

You're clearly more familiar with the budgeting lingo than I am. What are class D and A?

> Risk analysis usually accompanies these budgets to establish contingencies.

Likewise I have never done any risk analysis. How does it work? Got any examples or study materials?

We love to have people come in with deeper knowledge to challenge and improve the vocabulary.

**Comment by fosterlynn** [comment]
I think this is approximately (exactly?) where @elf-pavlik was trying to go in the discussion of Intents, see bottom of this comment https://github.com/valueflows/valueflows/issues/217#issuecomment-392538314.

I'm interested in working this issue out also in conjunction with the Intents that are listed as offers and/or requests.

**Comment by bhaugen** [comment]
Looks like this is class D and A:
https://carleton.ca/fmp/our-services/construction/estimates/
> Class “D”: A class “D” estimate is prepared when a project is at the “Conceptual Design” stage. 
> Class “C”: A class “C” estimate is prepared when a project is at the “Preliminary Design” stage. 
> Class “B”: A class “B” estimate is prepared when a project is at the “Detailed Design” stage.
> Class “A”: A class “A” estimate is attained when the bids for a project have been received, evaluated, verified, and the award of a contract has been made.

**Comment by bhaugen** [comment]
I think we are at the conceptual design stage here...

**Comment by nogo10** [comment]
Risk analysis is an estimate (quantitative and qualitative analysis) of risks to a project life cycle. Ie. probability and impact on  a project translated to a contingency fund. 
Example calculation: Risk(a) -> % of occurence x $$value of impact on project. For some project the number of risks are extensive with contingency fund up to 25% of project value. A more thorough analysis is carried out by the insurance industry.

**Comment by bhaugen** [comment]
@nogo10 
> Risk analysis is an estimate (quantitative and qualitative analysis) of risks to a project life cycle. Ie. probability and impact on a project translated to a contingency fund.

I get contingency fund, but what is the analysis usually based on? SWAG or something like threat analysis where specific risks are identified and calculated based on specific occurrence info? Like, how detailed do people usually get?

E.g. we're discussing this topic with a solidarity agriculture group now. Agriculture can have a variety of risks, like where we are, given climate change making the region wetter than usual, farmers are having trouble getting their grain crops harvested because the moisture content is too high.

Do you Solawi budgeteers do any risk analysis in your budgets?

**Comment by nogo10** [comment]
Each risk s evaluated of terms of probability (statistics , unknowns, predictions etc) and impact (as a cost). A risk analysis to be useful in construction, include mitigation measures as a cost item.  For agriculture it would be somewhat of an insurance calculation; although it may be similar.

**Comment by bhaugen** [comment]
I tried to reply to @yova over in https://discourse.solawi.allmende.io/t/clarifications-about-the-solawi-model/345/2 but got trapped by the permissions.

Here's my attempted response:

 Continuing the discussion from [Clarifications about the Solawi model](https://discourse.solawi.allmende.io/t/clarifications-about-the-solawi-model/345/2):

I was trying to reply to @yova 's reply to me, but did not see a reply affordance. Hope this works.

> One basis of the Solawi approach is to try mitigate the dichotomy of farmer and consumer, mainly with co-working days for consumers on the farm and the like.

That occasionally happens with CSAs in the US, but it is rare, and mostly the farms are like private businesses that hope they will attract enuf subscribers to cover their costs.

The idea of doing budgets and potentially rounds of membership commitments until they meet the budget costs seems to be an advance in the sense of collective responsibibiity, The farms that are actually owned by the members seems like yet another advance.

**Comment by almereyda** [comment]
a meta reply with direct responses

@bhaugen Thank you for the definition of *budget*! I was long missing that. I have reused it for the concept https://base.transformap.co/wiki/Item:Q240
The design stages also seem useful. 

@nogo10 From your last comment, may I safely deduce that the primary concern of accounting systems, may they include a forecast and budgeting, or not, are costs?

in general it seems we are closing the discussion

* [Creating a domain and data model and finding a suitable representation - Solid Base / IO2 - Forum des Netzwerks Solidarische Landwirtschaft](https://discourse.solawi.allmende.io/t/creating-a-domain-and-data-model-and-finding-a-suitable-representation/337/34)
* [Ontology for SFS budgets (#12) · Issues · SolidBase / SolidBase · GitLab](https://lab.allmende.io/solidbase/solidbase/issues/12#note_9727)

with questions around how to import simple CSV into these sophisticated representations, and how we can map our use case to the [xBRL conceptual model](http://xbrl.squarespace.com/conceptual-model/) and the [Financial Report Ontology FRO](http://www.xbrlsite.com/2015/fro/).

I have further made a claim to continue to develop in direction of Value Flows, to accept it as an active constitutive outside and constraint that has more generative, negentropic outcomes for SolidBase, in comparison to what we gain in velocity when omitting it as a distracting side force.

* [The SolidBase budgeting use case for Value Flows accounting - Solid Base / IO2 - Forum des Netzwerks Solidarische Landwirtschaft](https://discourse.solawi.allmende.io/t/the-solidbase-budgeting-use-case-for-value-flows-accounting/346)

For our case, @fosterlynn also proposed to simply call *Activity* [*Process*](https://discourse.solawi.allmende.io/t/creating-a-domain-and-data-model-and-finding-a-suitable-representation/337/31?u=yala). What would speak against reusing the VF concept here? *Function* was the viable and common compromise between specificity and generality. Then the link to *Process Classification* is also much more intuitive.

If Effort, Intent or Estimate are the same, and could be subsumed as Cost (from above), is it fair to call them Resources, no matter if they exist or not? Just asking, since a similarily intuitive correlation with *Resource Classification* from Lynn's model ([in WebVOWL](http://www.visualdataweb.de/webvowl/#iri=https://github.com/valueflows/valueflows/raw/94930bd1debe6ef98c5ec4104a4eeee100685bfc/release-doc-in-process/budget.ttl)) could happen.

**Comment by fosterlynn** [comment]
>For our case, @fosterlynn also proposed to simply call Activity Process. 

Actually, I didn't mean to make that firm of a proposal. :)  But I do like it in that it simplifies the VF model (vs adding Function), and we have thought that we will need nesting of processes into higher levels, which @bhaugen has explained is not exactly the same as a hierarchy driven by process classifications, because with nesting, you can arrive at a higher level process knowing the inputs and outputs at the higher level without being bothered by intermediate resources produced and then consumed.  And Process/Function follows the same I-P-O pattern as Process.  But I don't feel like I have completely proved out to myself that there aren't reasons in the model that make it too different from our Process.  And of course within VF, we would need to discuss first, and that will likely take longer than you have, so you in SolidBase will need to decide.  But personally I like it enough to go with it in the SolidBase Solawi situation and see what happens in VF.

>If Effort, Intent or Estimate are the same, and could be subsumed as Cost (from above), is it fair to call them Resources, no matter if they exist or not? Just asking, since a similarily intuitive correlation with Resource Classification from Lynn's model (in WebVOWL) could happen.

I don't think we can call the Effort/Intent/Estimate thing Resource, as it is more the edge and not the node.  EconomicResource is already defined into VF (from REA) as something that "exists" on the observation layer, even if all you know about it is its ResourceClassification (not inventoried for whatever reason). I see the Estimate thing as more the EconomicEvent equivalent in terms of repeating the pattern of REA at the budgeting level.  I started exploring if we could use Intent exactly there as part of a budget, as well as part of a Listing (like for timebanks, @matslats small ads, etc.)  If so, then an Intent can be the inputs to a Process/Function, and possibly the outputs also as part of the budgeting process.  (I think even for some supply-driven use cases, you will want to calculate the generally expected outputs to understand what there will be to split up.)

I still think it is fine to reference ResourceClassification from this thing, you mostly don't know the resource level info in the planning layer.  Like we directly reference RC from Commitment already.

Regarding the term Cost, it might work for you.  But the term also kind of implies money, which @elf-pavlik has always correctly reminded us is short-sighted.  Even within the SFS space, I'm willing to bet that there will be use cases not that far away where people are all contributing work and receiving food, and the translation into money as an intermediary won't be necessary.  Or contributing various different kinds of resources but the translation is into hours as the intermediary rather than a currency.

>I have further made a claim to continue to develop in direction of Value Flows, to accept it as an active constitutive outside and constraint that has more generative, negentropic outcomes for SolidBase, in comparison to what we gain in velocity when omitting it as a distracting side force.

I really hope this possible collaboration is productive for all efforts! It is always hard to balance the immediate needs and the future interoperability.  And @almereyda I appreciate that you have stuck with this from the very beginning, and even pre-beginning :blush: , always looking for synergies.

**Comment by almereyda** [comment]
The last question that remains with me before we can successfully decouple again: How do we map our terms to other vocabularies, like Value Flows *and* xBRL? It seems we can learn from their topologies in our modeling praxis, but how does it translate back to receive feature parity? In short: which are minimum, sufficient components of a budgeting model, that *must* be present for it to be called a budget?

I see here:

- the Agent
  an individual or an organisation
- the Roll-up of Forecast Accounts
  with *incoming* and *outgoing* sections - there may be more accurate accounting terms for this
  *total balance* - as the grand total below the roll-up
  - The debated Function / Process may as well simply be an Account, but one that is able to stretch into the future?
  - I agree Cost is too overloaded from financial discourse, esp. since we are working with sovereign economies
- the Intent
  may be in a metastable superposition between being determined, and being expressed - very much like the promise pattern in programming, or Schrödinger's cat.
  - This term would also leave it open to reuse *the same model* for accounting purposes, in so they can be presented next to each other.
  - Estimate would rather narrow its use down, but be more specific on the budgeting use case.
  - Either would be useful to decouple from an eventually introduced Currency..
- the Accounting Period / Interval

An answer could be a list of conceptual terms, but also a topology of their relations.

In the end I feel we must answer to ourselves if it is possible to model budgeting cases *without* considering accounting, and with it accountability, at all.

**Comment by nogo10** [comment]
By way of contextualizing Budget and planning with a use case, here is a project structure of modern construction from inception to delivery in simplified form:

1 Project inception stage (basis, need, demand)
  Definition phase scope

2 Project identification stage:
  Initiation phase
  Feasibility Phase
  Analysis Phase with Class D estimate
  Risk analysis and contingency planning
  Identification close out phase

3 Project delivery stage:
  Planning Phase
  Design Phase
        Professional Services Procurement
        Analysis of Project Requirements
        Concept Design Proposals with Class C estimate
        Design Development with Class B estimate
  Implementation Phase
        Contract Documents
        Pre-Tender Class A estimate
        Tender Call, Bid Evaluation & Construction Contract Award

  Construction Contract Administration
  Consultant Contract Administration
  Delivery Close Out Phase
  Operations and maintenance life-cycle

As you can see, estimates are used leading up to tendering and often does continue in change orders , directives and  scope change as 'on the ground' unforeseen conditions arise (hence the previous risk analysis).

**Comment by bhaugen** [comment]
@nogo10 thanks a lot! What would be an example of a construction project that would go thru all of those phases? For example, our last construction project was an attached greenhouse with guest room and bathroom.  We went thru some of those phases, but the project delivery phase was not so formal and we talked a bit about some risks but never did any real risk analysis or contingency budgeting.

Is the degree of formality dependent on scale of project and size of budget, or who's in charge, or degree of difficulty, or what?

**Comment by nogo10** [comment]
@bhaugen  the formality does apply to project scope/size. Small projects compress or forego some steps.

**Comment by fosterlynn** [comment]
Thanks @nogo10 for the PR !  For others' info, you can read his construction use case here: https://github.com/valueflows/valueflows/blob/master/use-cases/construction-commons.md.

**Comment by fosterlynn** [comment]
After some discussions with the SolidBase gang, this is where I ended up with what might work for VF.  Needs more work on properties, definitions, possibly naming, and integrating it with existing models and with proposed Intent models. But meant as food for discussion.
![budget-solawi](https://user-images.githubusercontent.com/3776081/47620658-94cc7680-daba-11e8-9eb8-11390d4fba05.png)
![budget-solawi-2](https://user-images.githubusercontent.com/3776081/47621432-c8f96480-dac5-11e8-938a-f194fb34c883.png)

**Comment by bhaugen** [comment]
Example of nested processes:
![nestedprocesses](https://user-images.githubusercontent.com/117439/47622554-4330e580-dad4-11e8-903d-0fa82e803f9d.jpg)

The nest represents growing carrots. The arrows on the left are inputs to the nest, and then go into individual nested processes. The tractor is used in each of the nested processes for a short time. The field is used all the time. The seeds are an input to the first process. The arrows between the nested processes do not appear outside the nest. The carrots come out of the nest.

**Comment by elf-pavlik** [comment]
> Regarding the term Cost, it might work for you. But the term also kind of implies money, which @elf-pavlik has always correctly reminded us is short-sighted. Even within the SFS space, I'm willing to bet that there will be use cases not that far away where people are all contributing work and receiving food, and the translation into money as an intermediary won't be necessary. Or contributing various different kinds of resources but the translation is into hours as the intermediary rather than a currency.

:+1: 

> A lot depends on what do you want to do with it besides come up with a total amount of money.

Myself I would only think of 'total amount of money' as something helpful in transitional phase and related to [Crowdfunding - In-kind + Monetary Hybrid](https://github.com/valueflows/valueflows/blob/master/use-cases/crowdfunding-in-kind.md#in-kind--monetary-hybrid)

I think one in general should draw a line between calculating all non currency dependencies, possibly following [Dependent Demand](https://www.valueflo.ws/appendix/dependent-demand.html). And gathering potential proposals of exchanges which nowadays will often include ones relying on some mainstream currency but I believe we need that more and more proposals will rely on other tools for managing reciprocity.

Since one has to calculate all the dependencies no matter of how one will approach arranging exchanges to secure them. I think we can consider it independently. Later one can have special case of finding exchange proposals relying on specific currency and reducing budget to a quantity of that currency needed of all the exchanges. At the same time more general case can include exchange proposals using any number of currencies, exchange chains etc.

Once again, I recognize that such special case focusing on single currency will make a pragmatic compromise for many people in near future as we transition to more diverse economic environment. At the same time focusing just on this special case I consider shortsighted and myself will always make sure that we also we design for the general use case. In case of Solawi I think we should at least start with anticipating work as part of exchanges. Later use of vehicles and combined service of transportation.

**Comment by bhaugen** [comment]
> Later very likely use of vehicles, spaces and combined service of transportation.

That's happening now around us, both with arrangements for combined transportation by friendly farms, and also by food network organizations, and in one case, a small-farm transportation service called Small2Small, and in another, a proposal for a ride-sharing service for food boxes as well as people.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/284.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
