### ISSUE TITLE
Errors running ValueFlows.owl in Protégé

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#294]
From tester: 
> I encoutered an error while trying to load the file in Protégé 3.5
> I can load it with Protégé 5.x, but Protégé 4.x and/or 5.x are not suitable for the instaciation process. I mean, it is possible, but NON useful at all ...

<img width="636" alt="errormessage" src="https://user-images.githubusercontent.com/117439/48949115-7eb8a700-eefc-11e8-85c7-74e0d89c2c92.png">

**Comment by elf-pavlik** [comment]
Where did this person get `.owl` file? OWL has various syntaxes and I don't even know if official `.owl` file extension registered with IANA exists.

![owl](https://www.w3.org/TR/2012/REC-owl2-overview-20121211/OWL2-structure2-800.png)

If this person uses old tooling maybe it expects `RDF/XML` format.

**Comment by babonet13** [comment]
I got the file from here : http://eelst.cs.unibo.it/apps/LODE/source?url=http://www.essepuntato.it/static/tmp/0

**Comment by elf-pavlik** [comment]
I think it just proxies this file https://raw.githubusercontent.com/valueflows/valueflows/master/release-doc-in-process/all_vf.TTL

Can your Protégé load turtle files?

**Comment by fosterlynn** [comment]
This is the definitive source that we use to create [this](http://www.essepuntato.it/lode/owlapi/https://raw.githubusercontent.com/valueflows/valueflows/master/release-doc-in-process/all_vf.TTL) spec, which we test compilation using [webvowl](http://www.visualdataweb.de/webvowl/): 

https://github.com/valueflows/valueflows/blob/master/release-doc-in-process/all_vf.TTL

But given the stage of the spec, "definitive" is a little loose, as some of these do get re-discussed.  I think it would be useful to start putting a status on each element so people know how stable they are.  And probably useful to publish the turtle version as a spec on the site.

@babonet13 btw thanks so much for showing up here!  You are a (maybe unwilling, I don't know) guinea pig for us, because the spec has not been used much in an automated way.  But this is extremely helpful, and we will try to recriprocate by helping you as much as we can.

Also just to note, the stated source https://w3id.org/valueflows# we haven't done anything with either.  It is todo, and if you want to use that, we'll do it sooner rather than later.

@elf-pavlik please clarify if I have mis-stated anything.

**Comment by babonet13** [comment]
Yep, It seems to be the very same files !
Turtle is not in the import list ... but I'm ready to test differents import format ...

<img width="402" alt="capture d ecran 2018-11-23 a 17 19 07" src="https://user-images.githubusercontent.com/20139338/48952864-11c8ff80-ef44-11e8-8acc-0d942384c399.png">

**Comment by elf-pavlik** [comment]
You could try converting turtle to RDF/XML using something like http://www.easyrdf.org/converter

**Comment by babonet13** [comment]
Seems working ... 
... except the link between prefix and namespace 

<img width="423" alt="capture d ecran 2018-11-23 a 17 37 40" src="https://user-images.githubusercontent.com/20139338/48953553-7f762b00-ef46-11e8-82e8-28179c7b7f85.png">

**Comment by elf-pavlik** [comment]
Actually we don't serve the ontology properly from namespace URL. We should fix this one!

**Comment by babonet13** [comment]
At this moment are you using this ontology :

**Comment by bhaugen** [comment]
@babonet13 I tried to answer this in our holo chat, but will repeat some of it here or the public record.
> At this moment are you using this ontology :
> 
> * Just in remplacement of a "paper" specification
>   (Where this ontology is just a guideline for developer who write the code)
>   OR
> * As a formal component in a ontology-driven application context
>   (Where the code of your application is fully driven by this ontology)
>   ?

Somewhere in between. Definitely as a guideline for software development, but also as a working vocabulary for communication between different apps, which was one of its original motivations.

Nobody here has developed an application fully driven by this ontology, but  [Wim Laurier](https://inno.com/person/wim-laurier/) and friends are working on something like that using their representation of the REA ontology, which is not the same as VF, but VF is mappable to theirs.

**Comment by elf-pavlik** [comment]
Turns out that we serve the ontology, request just needs to do proper content negotiation.
https://github.com/perma-id/w3id.org/blob/master/valueflows/.htaccess
