### ISSUE TITLE
Categorizing / classifying and specifying work and services.

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#300]
Capturing from https://github.com/valueflows/valueflows/pull/296#discussion_r236713077

> @elf-pavlik I would not use `ResourceSpecification` since we don't reference any resource from *work* flows and this would just make everything more confusing.
Only flows which at event stage will reference an actual resource with *affects* should use `vf:resourceConformsTo` and reference specification of a resource which event will reference using `vf:affects`.

**Comment by elf-pavlik** [comment]
For quite some time I would like to explore 'expanding' *work* flow into a process that outputs a *service* and takes as input *work* time of a person as well as *use* of this person skills. This way `vf:ProcessRecipe` that will land with #296 could get used as clear specification of a service.

This might work with other services, let's say mowing a grass requires inputs
* 1h work
* 1h use of string trimmer https://www.wikidata.org/wiki/Q1340233

Recipe of that process seems like a clear way to specify a service. While for product static `vf:ResourceSpecification` makes sense, for dynamic services (which for me include work) `vf:ProcessRecipe` itself looks reasonable to specify / define a service.

**Comment by elf-pavlik** [comment]
>> Could you please amend that fully automated post creation example to add some work flows?
```
ResourceSpecification
--id: 'rs1-post'
--name: 'Post'

ResourceSpecification
--id: 'rs2-image'
--name: 'Image'

ResourceSpecification
--id: 'rs3-text'
--name: 'Text'

ResourceSpecification
--id: 'rs4-designwork'
--name: 'Graphic Design'

ResourceSpecification
--id: 'rs5-writingwork'
--name: 'Writing (EN)'

RecipeProcess
-- id: 'recipeprocess1'
-- name: 'Write Post'

RecipeProcess
-- id: 'recipeprocess2'
-- name: 'Create Image'

RecipeProcess
-- id: 'recipeprocess3'
-- name: 'Format Post'

RecipeFlow
--id: 'recipeflow1'
--action: produce
--resourceConformsTo: rs1-post
--outputOf: recipeprocess3

RecipeFlow
--id: 'recipeflow2'
--action: produce
--resourceConformsTo: rs2-image
--outputOf: recipeprocess2

RecipeFlow
--id: 'recipeflow3'
--action: cite
--resourceConformsTo: rs2-image
--inputOf: recipeprocess3

RecipeFlow
--id: 'recipeflow4'
--action: produce
--resourceConformsTo: rs3-text
--outputOf: recipeprocess1

RecipeFlow
--id: 'recipeflow5'
--action: cite
--resourceConformsTo: rs3-text
--inputOf: recipeprocess3

RecipeFlow
--id: 'recipeflow6'
--action: work
--resourceConformsTo: rs4-designwork
--inputOf: recipeprocess2

RecipeFlow
--id: 'recipeflow7'
--action: work
--resourceConformsTo: rs5-writingwork
--inputOf: recipeprocess1
```

If we take example *graphic design* - http://www.wikidata.org/entity/Q185925

1. It gives a nice example of simply using taxonomy reference, I see calling it a *Resource Specification* as quite a streach.
2. I would consider it a *skill resource* and in this case using `vf:resourceClassifiedAs` makes sense

At the same time what if process requires work with more skills. For example to bake pie operating an oven and operating mixer. Either one person or two people could do this job, in case of oven and mixer one person could actually do it in concurrent way. If two people do it two work events make sense, if one person does it, we would not have 2 work evens with overlapping duration since this would in a way double count the time.

Services could come here helpful. Those two *use skill* requirement would either end up in a sub process of a one person providing a service (stay occupied + use 2 skills). In other cases it could end up in two sub processes of two people providing their services (stay occupied + use 1 skill each).

One could also *improve* such personal *skill resource* by taking courses etc.

**Comment by fosterlynn** [comment]
>I think if someone just needs a reference (IRI), taxonomy items provides just that. I understood that you proposed a ResourceSpecification for situations where someone needs to all kind of attributes one would use on an instance of EconomicResource but wants to describe just the concept of such resource.

I can agree that if people want just a label picked from a public taxonomy, then that is fine.  I can also see that it is OK if they have picked any number of classifications from such a taxonomy, even none, if they have a description.  Especially for intents, but also for commitments and events.  Except for recipes I think we want to ensure one and only one resource classification or specification, described in whatever detail or lack of detail people want, including only referencing a taxonomy.  What is the best way to model all of that for rdf?  

So, how about if a recipe requires a ResourceSpecification, with no required properties?  Everything else can reference a ResourceSpecification and/or can reference any number of classifications as iri's, or neither.

>Can you find an example from one of your deployments where you have work flow that references ResourceSpecification which specifies something else besides name/label?

You can't see under the covers on these for detailed properties, and anyhow, the app requires a bunch of the attributes, so it doesn't really help.  But if you want to get the flavor:

Here is a new one you might appreciate.
https://cryptpad.fr/pad/#/1/view/pBegE8FSTufleJkxUfFAUw/Ao3FiiezePGb8IvduHxyN3288cGh1w860MLtMMWntCg/
Recipe:
http://nrp.webfactional.com/accounting/xbomfg/16/

Here is a smattering from Sensorica, they use a lot of non-substitutable resource specifications, because they do R&D so have these groups of specific stuff which is defined more on the resource level.
http://nrp.sensorica.co/accounting/resource-type/143/ - a part
http://nrp.sensorica.co/accounting/resource-type/107/ - a design
http://nrp.sensorica.co/accounting/resource-type/249/ - business plan
http://nrp.sensorica.co/accounting/resource-type/32/ - a type of work
You can look around at all their resource types here: http://nrp.sensorica.co/accounting/resources/

**Comment by elf-pavlik** [comment]
> http://nrp.sensorica.co/accounting/resource-type/32/
> You need to save that search in a document and store it in the project folder

This looks like a good candidate to break into a sub process because of the requirement to *produce* some kind of report (document) which probably super process would *cite*

>  Except for recipes I think we want to ensure one and only one resource classification or specification, described in whatever detail or lack of detail people want, including only referencing a taxonomy.

I can understand it for *produce* recipe flow, but why do you need it for *work* recipe flow?

When it comes to *consume* recipe flow, probably single reference makes sense as well. But in case of lemon pie, lemon input https://www.wikidata.org/wiki/Q1093742 in most cases seems more than enough. Let's continue with non work or services related discussion in https://github.com/valueflows/resource/issues/26 where we have relevant prior conversation.

**Comment by fosterlynn** [comment]
> Let's continue with non work or services related discussion in valueflows/resource#26 where we have relevant prior conversation.

:+1:  sorry for wandering so far ot

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/300.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
