### ISSUE TITLE
Intents: "wholesale" vs "retail"

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#304]
I think some of what is making this hard (for me at least :sweat_smile: ) is the broad range of use cases.  Part of this span is how people generally treat "wholesale" vs "retail".  There is probably a gray area there too, but there is a difference between people engaged in production for others and people who are consuming it themselves or in a family situation, or even extended living situation.  At least a continuum.

Agents producing in some quantity for trading tend to have their supply chains already agreed to, with processes, quantities, etc.  This would apply to agents that are aggregating for re-distribution too.  If there is an exception and something else is needed, generally they would talk to their network of suppliers before making some larger broadcast of an intent.

Agents closer to the "consuming" end tend to have more of the one-off broadcast intents, or also regular agreements like CSA's etc.

This issue is to gather some thoughts about these differences, so we can see how they might affect the model.

**Comment by fosterlynn** [comment]
Without even getting to more industrial production (which we do still need of course for many things, think computers or laying cable across the atlantic) - here is a small example from my life.

I do produce catalog updates for a local buying club.  Even in this small local situation there are 2 levels of intents.  I get price lists from the veggie producers.  I aggregate those (the ones that meet the criteria of the buying club - as local as possible and organic), average prices, and load to the buying club software.

I'm pretty sure each of those veggie producers email their price list out each week to all the groups they have agreed to supply.  (Veggies available change fast, that is why it is that frequent.)  So they sell to this buying club, also to regional co-ops, and I don't know where else.  They don't tend to do "retail" (read smaller quantities).  One of them used to do a CSA on the side, but I bet that internally there was a transfer/exchange between the wholesale and the CSA sides of that farm.  So the price lists are the first set of intents.

Then I create another set of intents in the buying club software.  There is an agreement between members of the buying club to pay an additional percentage over wholesale costs to support the buying club expenses that are not covered by volunteer work.  So this set of intents is published inScopeOf this buying club and governed by this agreement.

(Re. less artisanal production, Bob has described the Saturn supply chain, which relied completely on agreements, and did not publish intents except to publish the production schedule, which the tiers of suppliers were expected to work towards.)

**Comment by elf-pavlik** [comment]
That sounds like an interesting use case: a producer providing to multiple distributors.
I think producer would have a single intent, for example estimated for a single week - *issue* 200kg of carrots. Then different distributors would make partial commitments that *satisfy* that intent.

I guess for that reason you might have proposed two quantities *intendedQuantity* and *availableQuantity*, where the second would get updated based on commitments already made.

**Comment by fosterlynn** [comment]
>I guess for that reason you might have proposed two quantities intendedQuantity and availableQuantity, where the second would get updated based on commitments already made.

That would be a good use case for that, yes.  And then the intendedQuantity would be the minimum order, basically.

**Comment by elf-pavlik** [comment]
>  And then the intendedQuantity would be the minimum order, basically.

I don't understand what do you mean by it.


If producer plans to harvest 200kg of carrots and offer all of them to distributors. They could simply have intent to: *issue* 200kg of carrots (`vf:intendedQuantity`).
As distributors make commitments: someone 50kg, someone 40kg etc. the intent could update:
`vf:availableQuantity` = `vf:intendedQuantity` - sum of all the commitments already made

Actually I would see clearer to use `vf:currentlyCommitedQuantity` to provide that sum and let everyone just do *intendedQuantity* - *currentlyCommitedQuantity* to get still available quantity.

If distributor wants to *receive* 300kg of carrots, they would have *intendedQuantity* = 300kg and as they make commitments with producers they would update their *currentlyCommitedQuantity* and let everyone compute how much they have still available for committing to. 

Just *availableQuantity* sound more like they have that resource available and doesn't work for me that well when they just 'stay available for committing to still receive that quantity of some resource'. We have availability of resource vs. availability of agent to make commitments. Something like *currentlyCommitedQuantity* which just provides sum of quantities from commitments already made, seems to me much clearer.

**Comment by elf-pavlik** [comment]
or just `vf:satisfiedQuantity` instead of `vf:currentlyCommitedQuantity` since we call relation between intent and commitment - Satisfaction

**Comment by elf-pavlik** [comment]
> It says intent 25# carrots (or 1 25# case carrots), reciprocal intent $25.

I think we still have misunderstanding about Intent and Proposal. While Proposal needs to provide a way to scale quantities of resulting Commitments in proportional way (two options #301 and #266 or others), creating Intents just for the sake of some specific proposal I would consider an anti-pattern.

Producer may plan for next month - optimal amount of carrots to issue 500kg in total (putting aside how they package it).

Based on recipes used to produce carrots, they can also estimate - amount of farming work - 10h which would possibly get represented as Intent, even with `vf:includeIn` broader intent for framing work.

They also may have commitments to issue various currencies: USD, Faircoin, LETS-Albuquerque etc.
Since currencies people involve for their 'exchange value' and not 'use value', they make a special case as in a way 'implementation detail'. So one can achieve same functionality through various different implementations, one can exchange in similar exchanges using various different currencies.

Still, based on however one uses existing commitments, currency accounts saldos, and trends in what one uses to exchange. One can still create similar 'optimal' estimate for each of those currencies
* *receive* 50 Faircon
* *receive* 200 USD
* *receive* 400 LETS-Albuquerque

Now for the single Intent: *carrots to issue 500kg* one can create at lest 4 proposals referencing it and one of the 4 other intents
* issue carrots & receive farming work
* issue carrots & receive Faircoin
* issue carrots & receive USD
* issue carrots & receive LETS-Albuquerque

#301 and #266 both provide a different ways for how one can calculate quantities of resulting Commitments

While those Commitments will have quantities specific to the Agreement, Intents referenced from Proposals have quantities specific to the Plan of an Agent and not to specific Proposal.

Of course plans needs to stay flexible to change, and Intents need a way to represent changes in those plans. For example that producer used to exchange some of the work for USD and now it gets exchanged for Faircoin, LETS-Albuquerque and actual carrots, they will not need to receive as much USD as they originally planned but they will need to receive more Faircoin, LETS-Albuquerque and maybe increase production of carrots (or issue less in non for work exchanges).

In similar way one can plan meals and transportation. Then estimate ingredients to cook oneself, and fuel for the car. Later one takes a rideshare and eats at dinning place and those original estimates will change as well.

**Comment by fosterlynn** [comment]
I'm thinking that offers and requests have some different thinking behind them.  I am thinking of offers, which are mostly as I described.  You are thinking of requests, like might come out of a plan.  These have more specific needs.

So an offer might usually be either a non-substitutable resource, or a general offer, say of plumbing work at 1 hr for xxx).  A request might be more like I need someone to do plumbing work for 5 hours.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/304.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
