### ISSUE TITLE
move assets specific to JavaScript & plain JSON to a dedicated repo

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#35]
I don't think we should make this vocab specific to JavaScript or JSON. I would like to move all .js files and JSON Schema descriptions to a dedicated repo

Relevant issues:
* https://github.com/valueflows/valueflows/issues/13
* https://github.com/valueflows/agent/issues/6

**Comment by fosterlynn** [comment]
@elf-pavlik I agree with you in general, although I'm not sure what it means in particular, and possibly don't need to know.  I do think we need to make sure that everything people tend to see and access is in the language it will be available to them in.  So hiding the js sounds good to me, as well as all places we are creating outputs from pieces of input.

I like the way AS has done it, where they have examples for each concept in 4 languages.  Like here: http://www.w3.org/TR/activitystreams-vocabulary/#dfn-relationship.  But that would be in the human readable doc I would think.  And for now, I'd like to stick to json-ld as what we offer.  Until we get some things up and running and have a need for something else.

**Comment by ahdinosaur** [comment]
@elf-pavlik having .js or .json files in our repos doesn't make this vocab specific to javascript or json, this is silly. i feel like i repeated myself enough in https://github.com/valueflows/agent/issues/6, so i have nothing more to say, other than that i'll be working towards improving my javascript files in `agent` to fully represent the vocab and be useful in [generating our context](https://github.com/valueflows/agent/issues/19) and generating our html docs, in the meantime i'm happy for others to work on these the manual way so when i do have time for automation i'll have a clearer picture of what to generate.

**Comment by ahdinosaur** [comment]
also i intend to `require` the javascript representation of `agent` directly in Holodex, so removing these means i have to redefine the vocab schemas somewhere else *in order to build an app on our vocab*, and for what reason?

**Comment by fosterlynn** [comment]
@ahdinosaur I'm still trying to understand this, and clearly you feel strongly about it.

So does that mean all of us would need to make any changes in the .js files to make things appear in the json-ld files people need to see?  And the picture?  And is the js easier to create than the jsonld?  

Is part of this being able to support more than one output format?  (For example the python library we picked for NRP uses rdf triples to generate all the common formats.)

I personally don't want to have to learn a whole other layer unless it is really really easier or necessary for another really good reason.

But my main concern is that people don't happen upon the js and json accidentally and get confused because they were looking for json-ld or something in LOD mode.  That has happened twice now and I think it set us back a few weeks one of those times.  (I don't know if the question of what repo affects this or not, just stating my overriding concern.)

Re. the picture, sorry I started anew.  It would have taken me some time to figure out what you were doing.  I should have said this is a place holder so I could get out some thoughts on the user doc.  I do consider it so, although I will give you all access to the cacoo drawing.  But it will be best to be able to generate the picture.

Question: Does this mean you have no plans for Holodex to take in json-ld?  I don't have a very clear mental architectural picture of what you are trying to do....

**Comment by elf-pavlik** [comment]
@ahdinosaur can you please document somewhere how do you precisely use JSON Schema in holodex?

IMO we will need to take some time to see how JSON Schema fits Linked Data vocabularies, hopefully we don't need to do it alone https://gitter.im/rdfjs/public?at=5617edce4e0fa3e55447da29

Possibly it may need to work the opposite way, generating JSON Schema from RDFS/OWL definition of vocab which now stays included in context.jsonld https://github.com/valueflows/agent/pull/39

**Comment by ahdinosaur** [comment]
> @fosterlynn: I don't have a very clear mental architectural picture of what you are trying to do.... 

yeah, i'm finding it difficult to communicate this, and more discussion doesn't seem to help, please give me time to actually get things working before we shoot it down (which might be a while as i other things have higher priority).

as a short final summary: the goal is a single source of truth for our vocabulary information which generates derivative truths ([JSON-LD `@context`](https://github.com/holodex/schema-jsonld-context), documentation, diagrams, hypermedia, [validators](https://github.com/mafintosh/is-my-json-valid), [databases](https://github.com/sethvincent/level-model), forms, etc.)

this is a longer-term strategy for when we have heaps of vocabulary information. i predict that managing multiple sources of truth is going to be a pain, while also i want a way to better automate the creation of apps built on our vocab (bam! instant CRUD API. boom! instant CRUD UI.) in the meantime, this isn't a pre-requisite for us to move forward, nor does it mean i'm somehow abandoning JSON-LD for Holodex.

but, if i have to persuade y'all of why i'm doing this, for my own self-protection i need to ignore y'all on this for now, otherwise i'm dragging myself into a bad space of mind. please trust me that i want what y'all want and this is how i plan to contribute.

**Comment by fosterlynn** [comment]
@ahdinosaur cool, totally agree with the objective, totally fine with working it out in practice.  And I don't want any of us to be in a bad space of mind for sure, so glad you are putting it out there.

So, as long as we are not working at cross purposes, and can just create stuff directly in the meantime, that's a good thing.  I'm totally fine with ditching things I create (pics, jsonld) when we have something else better that I can figure out how to use.  So, parallel paths, and I won't worry about that leg until you're ready?

In terms of this issue, I just looked at the repo structure, and I would suggest that the only thing we need to do is change the name of the directory called "vocab" to something that indicates it is an intermediate thing, not the vocab itself.  @elf-pavlik OK with you?  To me it is fine to put it where it is easiest to work with for Mikey, so long as we get rid of the confusion.
