### ISSUE TITLE
Our github workflow

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#41]
I'd like to reconsider our workflow.  And just so y'all know: this is the first project I have used pull requests, Bob and I just branch (or not) and merge.  So I'm learning.

I thought we were doing a fork and pull request work flow, although I might have completely misunderstood.  Last time I had to re-fork because I couldn't sync the upstream because history had been changed. I think Mikey is branching and issuing pull requests from the branch.  This seems like it would be a lot easier than what I am doing!

I would suggest we all to do the branch and pull request work flow.  Thoughts?

Reference: http://scottchacon.com/2011/08/31/github-flow.html

**Comment by ahdinosaur** [comment]
> I would suggest we all to do the branch and pull request work flow. Thoughts?

:+1:

btw, my open source workflow inspirations:

- [OPEN](http://openopensource.org/)
- [C4](http://rfc.zeromq.org/spec:22)

**Comment by bhaugen** [comment]
@ahdinosaur - I started doing fork-and-pull following this from C4:
> To work on an issue, a Contributor SHALL fork the project repository and then work on their forked repository.

And Lynn followed me, because I thought that was the rule. I think we should remove C4 from our workflow citations, because it conflicts with what we are actually doing, and publish some guidelines for contributors about the workflow we want to follow.

**Comment by fosterlynn** [comment]
From my link above, here is their suggested workflow:

*   Anything in the master branch is deployable
*    To work on something new, create a descriptively named branch off of master (ie: new-oauth2-scopes)
*    Commit to that branch locally and regularly push your work to the same named branch on the server
*    When you need feedback or help, or you think the branch is ready for merging, open a pull request
*    After someone else has reviewed and signed off on the feature, you can merge it into master
*    Once it is merged and pushed to ‘master’, you can and should deploy immediately

Let's basically follow this, with the exception that our master is not all that deployable at this stage of development, we're experimenting.  But let's say master is better than it was.

Good for everyone?

**Comment by ahdinosaur** [comment]
good with me, really enjoy that workflow and keen to add it to our CONTRIBUTING.md. :smiley: 

sorry @bhaugen for citing C4 while bending the rules because i'm lazy. :tanabata_tree: 

----

> Once it is merged and pushed to ‘master’, you can and should deploy immediately

i'm starting to setup continuous deployment here. so far, if you push to this repo's master, it will run [`npm run deploy`](https://github.com/valueflows/valueflows/blob/6901425bf1e962235fe31b292a79af5757e7b0c5/package.json#L7) which builds the README.md to index.html and pushes to [valueflo.ws](https://github.com/valueflows/valueflo.ws/)'s master. if you push to valueflo.ws master, it will also run [`npm run deploy`](https://github.com/valueflows/valueflo.ws/), which pushes everything to our [live dokku server hosting https://valueflo.ws](https://valueflo.ws). surprisingly, [this works](https://github.com/valueflows/valueflo.ws/commit/f5ff4808dc4f930896735425328280cbc8cf5437) and [our website is updated](https://valueflo.ws)!

at the moment i'm using [CodeShip](http://codeship.com) for this, but soon i'd like to write our own simple javascript bot to run on our dokku that can do the same process (but be open source and self-hosted) and also provide us with deploy results as a comment after a pull request is merged.

**Comment by bhaugen** [comment]
@ahdinosaur 
> sorry for citing C4 while bending the rules because i'm lazy. 

No prob. How much ceremony is required for a given situation is always a tradeoff. I'm good with  branch-and-pull.

**Comment by fosterlynn** [comment]
>i'm starting to setup continuous deployment here.

@ahdinosaur awesome, thanks!!

**Comment by fosterlynn** [comment]
Closing this, I think we have it.  I'll move some of this to a wiki page so it is documented.

**Comment by ahdinosaur** [comment]
it's in [my CONTRIBUTING.md pull request](https://github.com/valueflows/valueflows/pull/50), but i'm still waiting on feedback.

**Comment by fosterlynn** [comment]
@ahdinosaur sorry about that, missed your pull request.... :(  I'll take it out of the wiki.
