### ISSUE TITLE
One EconomicEvent quantity field for counting, accounting, and base for valuation

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#456]
It's difficult for me to understand all the backs and forths in issues like #446 , #452 , and #455 so I will cut to the chase.

I would like to have one and only one quantity field in EconomicEvents for the purposes stated in the issue title. Those will often be used in large aggregate computations where having possible exceptions for each item on which field to use will be slower and more error-prone and in general cause programmers to curse those who made those design choices.

The field has had different names: affectedQuantity, observedQuantity, ? I don't care what it is called, as long as it is one field and consistently named. People can add other quantity fields for other purposes if they want.

**Comment by bhaugen** [comment]
Oh, and y'all can call them properties if you want, too. I'm easy. I just want one and only one of them.

**Comment by elf-pavlik** [comment]
@bhaugen one of the use cases we'll look at *OuiKit*:
* https://github.com/valueflows/valueflows/blob/b63f16d8cf0d9fd920aa31ab7daf62fb2166233a/use-cases/ouikit.md
* https://www.matelo-evenements.org/membre/67

People can borrow/rent cups, bowls, cutlery for events.

If we do one *use* event it needs two dimensions:
* count of items
* duration of usage

If we have *check-in* and *check-out* events. They could have just the count of items but to calculate agreement one has two consider them as a pair and based on two events calculate duration of usage (borrowing or renting).

In the end to do *valuation* you need both dimensions *count of items* + *duration*, no matter if you capture it as single flow (event, commitment, intent) or split it in two and have to always consider a pair and calculate duration based on data from both flows in a pair.

**Comment by bhaugen** [comment]
I would do that as a resource which represents a collection of items and a quantity representing the duration of usage of that collection of items.

**Comment by bhaugen** [comment]
Lynn says I might not have understood the use case correctly. Regardless, I think I would check in and out a resource that represents a collection. Possibly more later.

**Comment by bhaugen** [comment]
> In the end to do _valuation_ you need both dimensions _count of items_ + _duration_, no matter if you capture it as single flow (event, commitment, intent) or split it in two and have to always consider a pair and calculate duration based on data from both flows in that pair.

Valuation in our experience is often a complex calculation, but then we put the computed value on the event, so after the value of the event has been computed, it's now one field again. Don't know if VF wants to add a value field to EconomicEvent or not, but in implementations, I would do that.

**Comment by elf-pavlik** [comment]
@bhaugen we will write this use case later today in more detail. Meanwhile you could maybe suggest how to represent:
* lending / renting 100 cups for 2 days
* lending / renting 50 cups for 6 days

I think one needs either one simple quantity per dimension: count & duration
Or use complex units that combine multiple dimension: cups/day

For the sake of generating exchange agreements it may work the same. But for keeping availability schedules one needs beside the duration also clear way to position it on the timeline. For that just cups/days doesn't help.

**Comment by bhaugen** [comment]
@elf-pavlik 

I'll comment on this issue first.
> for keeping availability schedules one needs beside the duration also clear way to position it on the timeline.

You have a time field (or maybe more than one time field) that can be a time interval positioned on a timeline, right?

> I think one needs either one simple quantity per dimension: count & duration
Or use complex units that combine multiple dimension: cups/day

I had not considered cups/day. Or more generally counting units per time unit. I guess it depends on what the numbers are used for. 

Is this a rental exchange where the renters would pay for the number of cups for the number of days? In that case, cups/day might be an accurate measure.

Or is the renting agent more concerned with how many cups are gone and when they are due to return? That's usually some kind of agreement. In that case, if you have checkout and checkin events, I would checkout and checkin the number of cups. The time field or fields can handle the expected duration if it is not specified in an agreement.

I think before finalizing this I'd also like to see how it compares with equipment usage.  I feel like these are all related and I might be inconsistent with myself now and then.

**Comment by elf-pavlik** [comment]
> That's usually some kind of agreement. In that case, if you have checkout and checkin events, I would checkout and checkin the number of cups.

In that case you have always consider a pair of events when you 'evaluate' something. One can't just evaluate the checkin by itself or the checkout by itself, it takes the pair to represent an actual economic activity - renting / lending x cups for y days.

**Comment by elf-pavlik** [comment]
![count-x-duration](https://user-images.githubusercontent.com/876431/52742714-fc410000-2f9d-11e9-8b8e-20c6a3ce7967.png)


First graph tries to illustrate that for 'valuation' of usage, in many cases we would have
4 items * 1 hour == 1 item * 4 hours == 2 items * 2 hours

Second diagram tries to show how schedule would look like with commitments to *use* certain quantity for certain amount of time. We could also think of *reserve* action which doesn't mean actual use but still blocks the schedule as well as breaking things up in pair of flows like *check-in* and *check-out* where 'valuation' would have to always operate on the pair and calculate the duration based on information on both flows used to express one economic activity.

**Comment by elf-pavlik** [comment]
First graph also relates to planning from recipes, all three would harvest the same amount (kg) of apples
* 4 people using 4 ladders and 4 baskets in 1h
* 2 people using 2 ladders and 2 baskets in 2h
* 1 person using 1 ladder and 1 basket in 4h

Recipe could stay based on 1 person using 1 ladder and 1 basket for 1h and to plan process one could scale it based on counts as well as duration. In the end one should be able to get from it any of the 3 different plans above.

**Comment by fosterlynn** [comment]
Your graph seems useful, although I'm not sure of all the implications.  But for scheduling and planning for sure.  But also just noting it is not universal, like the "mythical man month". :)

**Comment by fosterlynn** [comment]
>I would like to have one and only one quantity field in EconomicEvents for the purposes stated in the issue title. (One EconomicEvent quantity field for counting, accounting, and base for valuation)

@bhaugen feels pretty strongly about this.  He is the one with the years of experience in working with this domain specifically, including different kinds of manufacturing, supply chains, MRP, ERP, etc.  He wrote the code that traverses value flows in NRP for various purposes, and the code that creates plans from recipes.  All of that from deep experience that nobody else in VF has, and not all that many people in general have for that matter.  I was willing to compromise on this to move forward, Bob is not.  And I think he is right.

Occasionally you @elf-pavlik , and I also, have felt equally strongly about some issue or vocabulary question.  When you felt that way about "type", after lengthy discussion where a number of people gave their views, I backed your right as a core contributor to block the word "type" because you felt very strongly about it, and it was based in your rdf experience, even though I and most everyone else disagreed.  I think we should honor that consensus mechanism in this case too.  

So, I think we should figure out how to do this with one quantity field for counting, accounting, base for valuation.  Sometimes it will have a time-based unit.  There can be other properties, but it won't depend on whether there is an inventoried resource or not, and it won't depend on if the unit is time-based or not.  It will be the quantity for counting, accounting, and base for valuation.  I think in every example people can figure out what that is for them.  And it can be a compound unit like count per year or whatever.  But there will be one same named quantity property in all events (and commitments - intents TBD) that has that main purpose.  That quantity is about the flow, not the resource.

**Comment by elf-pavlik** [comment]
Maybe @bhaugen could propose his take on this snippet for [used 12 ouikits for total of 6 hours in October 2018](https://github.com/valueflows/valueflows/pull/458#issuecomment-469484754)

> And it can be a compound unit like count per year or whatever

We could look at such units eg. `unit:Number / unit:Hour` but then we would end up with 3+ quantitative values:
* `involvesQuantity`
* `temporalLength` + plus optional `hasBeggining` and `hasEnd`
* `accountingQuantity` (which sounds like 'service units' we have discussed on chat)

We would need how this fits into planning and agreements.

**Comment by fosterlynn** [comment]
>We could look at such units eg. unit:Number / unit:Hour but then we would end up with 3+ quantitative values:

QUDT has several of them already: I see NUM-PER-YEAR and SAMPLE-PER-SEC with a quick look.  I think that is the way to define those compound units.

In the ouikit example, I just used the number of kits, thinking that is what would be the key quantity for say a recipe for an event.  But it depends on the needs.  If you think this example requires something like "kits per hour" for its measure, then that can be handled with a compound unit.  Generalized "number per hour" or something, probably something already exists?

**Comment by fosterlynn** [comment]
Taking the work example, accounting for a translation process.  Better name welcome!  But I'm looking for a name that doesn't have to imply a resource and can be used for different scenarios

Record the hours of work (due on certain date, but the person can do it when they want)
```
flowQuantity:
      qudt:unit: unit:Hour
      qudt:numericValue: 4
flowTime: 
      '@type': Instant
      time:inXSDDateTimeStamp: 2019-03-07T00:00:00-5:00
```
Record the number of words (again due on certain date)
```
flowQuantity:
      qudt:unit: unit:Word
      qudt:numericValue: 1000
flowTime: 
      '@type': TemporalEntity
      time:hasBeginning:
          time:inXSDDateTimeStamp: 2019-03-07T08:00:00-5:00
      time:hasEnd:
          time:inXSDDateTimeStamp: 2019-03-07T12:00:00-5:00
```
Record the hours of work which must be done on a specific calendar schedule
```
flowQuantity:
      qudt:unit: unit:Hour
      qudt:numericValue: 4
flowTime: 
      '@type': TemporalEntity
      time:hasBeginning:
          time:inXSDDateTimeStamp: 2019-03-07T08:00:00-5:00
      time:hasEnd:
          time:inXSDDateTimeStamp: 2019-03-07T12:00:00-5:00
```

**Comment by fosterlynn** [comment]
> used 12 ouikits for total of 6 hours in October 2018

If the requirement is to know kits/hour of usage, then this could work:
```
action: use
flowQuantity:
      qudt:unit: unit:Number-Per-Hour # may not be real qudt unit
      qudt:numericValue: 72
flowTime: 
      '@type': TemporalEntity
      time:hasBeginning:
          time:inXSDDateTimeStamp: 2019-03-07T12:00:00-5:00
      time:hasEnd:
          time:inXSDDateTimeStamp: 2019-03-07T18:00:00-5:00
```

The time would be needed for scheduling the different activities that needed the kits during the event.

**Comment by fosterlynn** [comment]
>used 12 ouikits for total of 6 hours in October 2018

If the resource had more than 12 kits in it, and you don't want to split or issue or transfer it or whatever it first, then how about this?  Assuming you also want to know the number of kits for some other reason, maybe for scheduling.  The idea is to have the one counting/etc. quantity always be the same named quantity.

```
action: use
flowQuantity:
      qudt:unit: unit:Number-Per-Hour # may not be real qudt unit
      qudt:numericValue: 72
involvedQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 12
flowTime: 
      '@type': TemporalEntity
      time:hasBeginning:
          time:inXSDDateTimeStamp: 2019-03-07T12:00:00-5:00
      time:hasEnd:
          time:inXSDDateTimeStamp: 2019-03-07T18:00:00-5:00
```

I feel like we still need some thought put into the "availability" needs. Could be part of the transfer discussion?  But if we can agree on having one "counting" quantity, we can settle on a name, and leave it for later.

**Comment by elf-pavlik** [comment]
Finding clear names which capture **the meaning of the relationship** between flow and quantitative value might take some trying. Still it looks that this example shows all the properties we see need for:

```yaml
action: use
accountingQuantity:
      qudt:unit: unit:Number-Per-Hour # may not be real qudt unit
      qudt:numericValue: 72
involvesQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 12
temporalLength:
      qudt:unit: unit:Hour
      qudt:numericValue: 6
time:hasBeginning:
  time:inXSDDateTimeStamp: 2019-03-07T12:00:00-5:00
time:hasEnd:
  time:inXSDDateTimeStamp: 2019-03-07T18:00:00-5:00
```

* `accountingQuantity` - something that @bhaugen requested, most of the time derived in some way from other quantitative values
* `involvesQuantity` - in case where flow references a resource with `involves` or classification / specification with `resourceClassifiedAs` / `resourceConformsTo` - the quantity of that resource involved in the flow
* `temporalLength` - in a way duration of the flow but not requiring continuity of the action
* `time:hasBeginning` & `time:hasEnd` - exact extent of the flow

I think given `accountingQuantity` we might not need `temporalLength`, we would need to see how it works with FC like example which might need both in case of translation services.

**Comment by fosterlynn** [comment]
>Finding clear names which capture the meaning of the relationship between flow and quantitative value might take some trying.

Often the case.  :)

>accountingQuantity - something that @bhaugen requested, most of the time derived in some way from other quantitative values

Most of the time not derived.  Almost never will there need to be more than one quantity.  I have never seen an actual use case that needed another quantity, and the made-up ones don't really make sense to me so far.  I think this property should be the main flow quantity.  Add other properties only if needed by people in a real use case.  Maybe document the option.  Keep it simple because mostly it is simple.

So, I don't really like that name, makes it seem derived or like a report.

And it would be great to also have one flow time property.

**Comment by fosterlynn** [comment]
Perhaps a question would be: what extra benefit do you see from creating different properties based on whether resources are affected, if it is a time, etc. - vs using one quantity property, with supporting quantities only if needed?  Is there anything that is not already known another way that is needed for subsequent processing?

**Comment by elf-pavlik** [comment]
When we already need two different quantitative values (two factors)
* amount of involved resource (related to its `vf:currentQuantity`)
* temporal information (extent / duration / length)

If we want to have one quantitative value (product of those two factors) to use for social accounting purpose, we need add it as 3rd value. If replaced those two factors with just the product, I don't think we can't guarantee ability to derive those two factors from that product.

This leaves us with needing three different properties. At the same time since non of those original two can get used for representing quantities like 
* word count - translations use case
* distance - taxi use case
It looks like we need three different quantitative values anyways and the social accounting one (service units) seems also fit for use in above two use cases.

When it comes to representing temporal entities. We need a way to represent both
* temporal extent with specific start and end
* temporal duration

We also seem based on that FC use case a way to represent length of non-continuous intervals. I see this one as another candidate where we can rely on that 3rd social accounting / service unit based quantitative value.

Given all above, I think we need 3+ properties to represent
1. amount of involved resource (related to its `vf:currentQuantity`)
2. temporal information (start & end || duration)
3. accounting / service quantity

In simpler cases one will use the same value for 3 & 1 or 2 & 1, in more complex cases one get 3 as product of 1, 2 and possibly other factors.

**Comment by fosterlynn** [comment]
>service units

What does that mean, can't remember that part of the chat?

**Comment by fosterlynn** [comment]
>This leaves us with needing three different properties. At the same time since non of those original two can get used for representing quantities like
>    word count - translations use case
>    distance - taxi use case

Why not?  What is the known user requirement for having different properties for these kinds of differences?  All of those minor differences can get handled by configuration as needed.  If you don't define them so narrowly, then one quantity field can work for all events, with supporting ones added as needed (no actually known use case in real life so far).

**Comment by elf-pavlik** [comment]
> All of those minor differences can get handled by configuration as needed. If you don't define them so narrowly, then one quantity field can work for all events, with supporting ones added as needed (no actually known use case in real life so far).

I don't know what configuration you refer to. We need to define property in a way that makes crystal clear the meaning of the relation. Two applications should not use the same property while meaning something different, this would work against interoperability.

Also any application can add any number of additional quantitative values using properties from any number of vocabs. Not all applications will understand what this quantitative value mean so they will silently ignore that property. We only need to focus on those affecting core VF based interpretation of data.

> Why not?

Because in our efforts to write YAML snippets for ouikits and other use cases, we have shown that we need more than one quantitative value to clearly represent things. I think we should keep working with those snippets and drive this exploration based on what information we need for what purpose.
* service quantity for social accounting
* temporal information for scheduling
* involved resource quantity to plan and keep track on `currentQuantity` (even while some part of it gets currently used)

I think we may struggle with resolving those issues because we haven't clearly specify requirements based on which data needs to get interpret.

> In simpler cases one will use the same value for 3 & 1 or 2 & 1, in more complex cases one get 3 as product of 1, 2 and possibly other factors.

Probably we will need to take a closer look at how Recipes work if 3 (service quantity for social accounting) gets derived based on quantity of a resource involved, temporal information and possibly other factors.

**Comment by fosterlynn** [comment]
>I don't know what configuration you refer to.

The knowledge layer, as well as things like distribution agreements and other kinds of agreements, should be able to configure things so that we can have a simple model on the observation layer, and apps know what to do with the data operationally and analytically.  Because people and groups defined what they need.  So time units and volumes and weights and counts are definitely different in the real world; material and immaterial resources, services, etc. have differences too; people will need to do unit conversions, etc; but if you go one level higher conceptually in your definitions, they can become one property easily because they are used for the same features and uses, they are frequently iterated over together in one big 'get', and everything becomes much simpler because you don't have to explain all those nuances in a hard-coded way.  And they will be a fraction of what exists if you define things at that level.  We can't presume to define that, we don't have enough use cases, and can't have enough use cases. 

>We need to define property in a way that makes crystal clear the meaning of the relation. Two applications should not use the same property while meaning something different, this would work against interoperability.

Again, that's why we need to define it at a level that can cover the economic value flows needs, which imo is a level higher than you are trying to define it.

>>Why not?

>Because in our efforts to write YAML snippets for ouikits and other use cases, we have shown that we need more than one quantitative value to clearly represent things.

I disagree, we haven't shown that. There is always a solution where one quantity makes sense, even the drills (which doesn't make sense in the real world), and the ouikits (which we are guessing at the real requirements).  I think when you are thinking about "clearly representing things", it is clear from some level of more specific definition, but doesn't reflect the actual needs of the vocabulary.

I would like to err on the side of simplicity and let people work with it, starting with something easy to understand and use and communicate with.  If people run into situations that one quantity won't handle, then we add something.  

Maybe part of the disagreement is also about how much should be user defined vs hard-coded?

**Comment by fosterlynn** [comment]
Specifically looking at these

> *    service quantity for social accounting
> *    temporal information for scheduling
> *    involved resource quantity to plan and keep track on currentQuantity (even while some part of it gets currently used)

First and third are the same, and the action and resource/specification have configuration to know if resources are incremented, decremented, or not.  (I don't understand "service quantity" though?)

So we have two, the quantity (first and third), and the scheduling information, which is the time property, not the quantity.  A quantity property and a time property.

I think that a lot of the configuration will affect lower level operations, so when the data gets communicated between at higher levels, it won't need .  Like operationally, say in Sensorica, the value equation (distribution agreement) has all the formulas to calculate distribution amounts based on the one quantity in events.  But at a higher level, you only want to know that input and output transformation events happened, income distribution events happened, and here are their quantities and their reciprocities.

Or, I don't see any reason that quantities in a recipe that create a plan need different quantity definitions than those that are recorded as inputs and outputs to a process which transforms resources.  And a quantity of a resource that is decremented when it is input to a process can be the same quantity property as a quantity that has no resource to decrement when it is input to the same process.

**Comment by fosterlynn** [comment]
Some thoughts about possible names we could use across flows.

countedAs, quantifiedAs (i like the latter better)

Another option to replace affectedQuantity just for events: reportedQuantity

**Comment by elf-pavlik** [comment]
I don't see problem only related to naming. While we can find one property specific to the *social accounting* requirement, other requirements sometimes need two or more properties. Let's try to keep moving forward with #471 and once we know what quantitative values we need for which requirement we'll worry about naming them all.

**Comment by fosterlynn** [comment]
Resolved per v.3, please re-open if needed later.
