### ISSUE TITLE
Adding optional locations to `EconomicEvent`; location properties

### ISSUE THREAD

**Issue by pospi** [valueflows/valueflows#486]
It seems like a good idea to enable this to me- it would be particularly pertinent in logistics in order to more accurately inform calculations of GHG emissions as a by-product of transporting resources from A to B.

**Comment by pospi** [comment]
I think the only curly requirements are to provide for multiple `location`s at the same coordinates, with different names- so that you can have "under the sink", "in the top drawer" as separate `Place`s. The spec looks pretty comprehensive, I'm not concerned about limitations. The bigger concern is pairing down what we really need to service as a minimum implementation vs the fully-featured version.

If there's an existing issue where this is better discussed, feel free to direct me that way. I know the group has been discussing new location ontologies for some time.

**Comment by elf-pavlik** [comment]
I recall recent comment on this old issue: https://github.com/valueflows/forum.valueflo.ws/issues/27#issuecomment-461827306

> I think the only curly requirements are to provide for multiple locations at the same coordinates, with different names- so that you can have "under the sink", "in the top drawer" as separate Places. 

I think 'same coordinates' depends heavily on their precision. https://wiki.openstreetmap.org/wiki/Indoor_Mapping shows maps inside of buildings.

Document I linked in my previous comment mentions https://www.w3.org/2017/sdwig/bp/#spatial-relations
>* Topological relations describe the relationships between geometric objects that are invariant to rotation, translation and scaling. As such, topological relations can support qualitative spatial reasoning without reference to the geometries themselves; for example, to assert that object A touches object B. These relations, also known as “spatial predicates”, include concepts such as: equals, disjoint, intersects, touches, within, contains, overlaps and crosses.
>* Directional relations specify the relative direction between object and reference. Examples include: left, in front of and astern.
>* Distance relations specify how far the object is from the reference object. Examples include: at, nearby and far away.

We already rely on OWL-Time for [Topological temporal relations](https://www.w3.org/TR/owl-time/#topology), so we can define that some flows or processes have to start at the same time (while not providing specific beginning for any of them), or that some flow happens before or after another one.

I think we may need at leas to specify that one place contains another place.

**Comment by fosterlynn** [comment]
Seems like we got a couple decision tracks emerging from the discussion.

1. We can go ahead and specify Location (or Place, but I like Location so that there isn't a resource or agent tinge to it, just location - but probably it is already in other vocabs so we can see what is out there).  And put some basic properties on it based on @elf-pavlik 's link. Might not be in the VF namespace, but it could go into graphql etc to kind of put a stake in the ground of what vocab we want to use.

2. We can decide if we want a location property on EconomicEvent.  I would like to do an example on that in order to see if that works for @pospi 's use case.  Seems like it might fit well for load and unload if transportation is the use case.  But we do already have it on EconomicResource, so I'd like to see it in action.

**Comment by elf-pavlik** [comment]
> Seems like it might fit well for load and unload if transportation is the use case. But we do already have it on EconomicResource, so I'd like to see it in action.

We can have commitment which doesn't involve specific inventoried resource but just references a classification or specification. Still this commitment may need to define specific place. I don't think we should rely on location of the inventoried resource, especially that inventoried resources can get moved around and we again have a problem with trying to figure out its location at the time of event, even more future location at the time of planned commitment or intent.

**Comment by fosterlynn** [comment]
>We can have commitment which doesn't involve specific inventoried resource but just references a classification or specification. Still this commitment may need to define specific place.

Good point.

Carbon footprint may be more complex too, and have other options, such as fuel input to the transportation process.  But I don't have any objections to adding it to flows.

What do you think about name?

And what do you think about defining a Location class with some properties?

**Comment by elf-pavlik** [comment]
I hope we can handle it similar like quantities. We would only define few properties capturing meaning of how VF constructs relate to some places. All the places related terms preferably will come from already existing vocab.

**Comment by fosterlynn** [comment]
Using this same issue to talk about the properties, since discussion already happened here.

I did a skim of the docs referenced here https://www.w3.org/2017/sdwig/bp/#c-spatialdatavoc.  Here is a simple rendition: https://www.w3.org/2003/01/geo/wgs84_pos# - that seems relatively standard.

Didn't see much in the way of textual address that is mappable.

Recommendation:  
* Use geo:lat, geo:long, geo:alt
* Keep our properties that reference a location.
* Maybe change our Location to be geo:SpatialThing????
* Add skos:note and vf:name and vf:address (for the textual address that generated the long and lat)

**Comment by elf-pavlik** [comment]
#510 already landed, #511 seems to have there rest. While we can start using it, I think we should expect it to stay *unstable* for some time.

**Comment by fosterlynn** [comment]
Closing based on PR https://github.com/valueflows/valueflows/pull/511.
