### ISSUE TITLE
Agent, Resource and Process don't need to stay disjoint

### ISSUE THREAD

**Issue by elf-pavlik** [valueflows/valueflows#508]
moving from https://github.com/valueflows/valueflows/issues/507

>> @elf-pavlik: While doing that I also lean more towards not treating agents, resources and processes as disjoint. So we can also treat agents as 'very high level process' which can have inputs and outputs. 

> @bhaugen: if you conflate agents with high-level processes, then do processes have agency?

> Or if you conflate resources with processes with agents, than do resources have agency?

> (To be more explicit, I think agents, processes, and resources are distinct concepts for very good reasons.)

Agents have agency and process have inputs and outputs. In some cases it comes very natural that some entities may have both. For example organizations that act as specific project and eventually deliver some 'outputs', they also can have 'inputs' which don't fit in some 'lower level' process. This may come clearer when we work further on budgets and composing processes. Also person can consume a meal as input, one could have more granular processes eg. montlhy life-work cycle etc. but I don't see why one can just have it as input as one's own lifelong process. So person can have aspect of agency, aspect of process and also aspect of resource. I can make agreement that someone will *load* me (pick me up) in one place and *unload* me (pick me up) in another place. At the end of this lifetime my body may also need proper *circular economy* treatment with some form of *consume* - eg. input of composting process. Before that I could also get *accepted* to hospital and hopefully *improved*, similar to a broken bike.

I don't think we should forcing creating separate entity for one's agency, one's processness, one's resorceness.

**Comment by bhaugen** [comment]
@elf-pavlik I understand better where you are coming from, but still disagree. 

We also have a disagreement with Bill McCarthy on some aspects of agents-as-resources. For example, when we worked with Sensorica, they required different skills for work inputs to processes: like electronic, chemical, and mechanical engineering were distinct skills and were not substitutable for each other. So we modeled skills as separate concepts that an agent might have, but not be. An agent might have more than one skill. These would be like cognitive characteristics, a concept with which I know you are familiar.

McCarthy treats skills as AgentTypes, something an agent is, not has, which we think is wrong and would become awkward. But then Bill has never developed an operational system.

**Comment by bhaugen** [comment]
> At the end of this lifetime my body may also need proper circular economy treatment with some form of consume - eg. input of composting process. 

At that point, you ain't got no agency anymore. Although your survivors might be acting from some plans you wrote down back when you did.

Likewise your excrement can either be a valueable resource or a noxious waste depending on whether you practice humanure or not. But your excrement is not you or an agent either.

> Before that I could also get accepted to hospital and hopefully improved, similar to a broken bike.

Or some medical services have been performed for you. But that does not make you into a resource.

One fundamental objection to humans-as-resources is that in slave systems, some humans are. I know that is not how you are thinking about these topics, but that was one of the first realizations I had when I first looked at REA, because I had been working with systems that had "human resources" and I thought agents with agency was a lot better...

**Comment by elf-pavlik** [comment]
> Or some medical services have been performed for you. But that does not make you into a resource

I don't think just *receiver* on a flow solves it since medical service which person *receives* could get performed on a pet or infant with developing agency or elderly person with crumbling agency. In each case same person could get listed as *receiver* but flow still may want to specify whose body it actually *improved*.

**Comment by bhaugen** [comment]
@elf-pavlik 
>>Or some medical services have been performed for you. But that does not make you into a resource

> I don't think just receiver on a flow solves it since medical service which person receives could get performed on a pet or infant with developing agency or elderly person with crumbling agency. In each case same person could get listed as receiver but flow still may want to specify whose body it actually improved.

True. But I'd like to model that differently than a bike.

The general connection here is that I am very reluctant to mess too much with REA, for reasons that might not matter to you, but do matter a lot more to me than RDF does, which might matter more to you. So this might be the source of some of our differences of opinion. And I don''t know how to resolve that in a principled way.

I have messed with REA before, several times, but in each case, I knew what I was doing, and got the changes either approved and accepted or at least tolerated as permissible by the larger REA community. I am pretty sure that conflating agents, resources, and processes would not be accepted very well. Beyond that, I don't like that idea personally, because I think it will cause problems with the systems we have created and want to create. I am pretty sure I can create test cases, but don't have time to that today (or tomorrow). Too much else happening in the realms of operational systems and local life.

As an aside, @fosterlynn and I just discussed at breakfast how - or if - REA could model all ecosystem relationships, as well as human economic relationships. Like clearly all critters have some agency. Pets and infants are interesting test cases.

**Comment by bhaugen** [comment]
@elf-pavlik re medical services: John Sowa, who is one of Bill McCarthy's mentors and colleagues in ontology work, uses the concept *Patient*:
>  The theme and the patient relations are both used to link the concept of an action to the concept of the thing that is acted upon. The theme of a verb (e.g. chase or catch) is not changed by the action, but the patient of a verb (e.g. eat) is substantially changed.

-from http://www.jfsowa.com/cg/cgonto.htm

Sowa uses the medical word "patient" for more than medical situations, but we could also use that word for VF medical service scenarios to differentiate from the Agent when for example the patient is an infant or a pet. 

I'm not sure how far I want to take this. The concept "patient" does not exist in the REA ontology but we could probly import it if we want and get it approved. I'm not proposing that we do, yet, but did want to respond to your use cases and also differentiate medical service scenarios from bike repair.

So consider "patient" as an addition to the discussion rather than a proposal, so far.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/508.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
