### ISSUE TITLE
Process vs Agreement vs ?

### ISSUE THREAD

**Issue by fosterlynn** [valueflows/valueflows#515]
In working on the transfer model, I find myself trying to use Process in ways that might push the boundaries of how it is currently defined (changes inputs into outputs).  But it does come in handy for tying together events besides the usual inputs and outputs.  These assume we will have one economic event representing a transfer, which I think we have tentative agreement on, but is not firmly decided.  

Examples:
* Checking out a library book - a transfer from the library to a person, a commitment to transfer it back, then later a transfer from the person back to the library, fulfilling the commitment.  These don't particularly require a Process, but it handily ties them together.  And doesn't have the downsides of trying to make the whole interval between checkout and checkin into one event.
* Transfer of a crypto-currency and the fee for the transfer to the 3rd party supporting the transfer (miner, server operator).  Could create a service output of a Process that makes the main transfer, and then exchange that service for the fee, under an Agreement.  Or could just put both transfers under one Process, and that is it, simpler.  Possibly could just put both transfers under Agreement too, without the service.  Not an exchange, but related transfers with some kind of "default" agreement, sort of.  But the initial transfer might also relate to an actual exchange agreement.

One thing that happens when putting transfers under a Process is that it is not clear what is an input and what is an output.  In some ways a Process that is about facilitating a transfer could have the transfer as an output, and whatever inputs are needed to do that would be inputs as usual (work, equipment, etc.)  Or we make a new property for this, like inputOutputOf or transferOf.  In any case, processing of transfer events as part of a value flow will have to know that there is an input and an output involved, whether part of a process or not.

@bhaugen points out that McCarthy has added "business process" as a concept, which can cover this sort of thing.  But noting: he doesn't have our Process in his model (he has Conversion, and also often uses EconomicEvent more broadly than we do, with Stockflow being our event).

In any case, I would like to either define Process a bit more broadly and use that, or create a new concept that is another container of related events but is not an Agreement or an exchange.  Thoughts?

**Comment by elf-pavlik** [comment]
> Transfer of a crypto-currency and the fee for the transfer to the 3rd party supporting the transfer (miner, server operator).

I think fee comes for moving (virtual shipping) of currency units between accounts (addresses). IMO one could make pure VF transfer of ownership which would get only recorded in datasets of agents. Units wouldn't need to get moved between accounts at all.

> One thing that happens when putting transfers under a Process is that it is not clear what is an input and what is an output.

Since transferring ownership only affects how rights get calculated and doesn't affect quantity (actually contained) of the resource, I don't think transfers would go as either inputs or outputs. Again, service for moving quantity between resources could come as output of a process.

> Checking out a library book - a transfer from the library to a person, a commitment to transfer it back, then later a transfer from the person back to the library, fulfilling the commitment. These don't particularly require a Process, but it handily ties them together.

This sounds for me like an Agreement, possibly using just *under* and non machine readable clauses what would happen if book would get damaged or returned after due date.

**Comment by gcassel** [comment]
I know I'm not here much but here are my three cents, and apologies if I'm missing any context or subtext.   Ownership is a resource, and I see transferring ownership as a process.  

I see transfer (of ownership *or* custody) as *transportation of social resources*, and I like for that to be closely analogous to transporting physical resources.   Transportation per se isn't transformation or transmutation; nonetheless it *changes resources*, and that change can (whenever desired) be indicated as inputs & outputs.    For example, *Resource A with Location Y* is *not* the same as *Resource A in Location X*; nor is *Resource A owned by Agent 2* the same thing as *Resource A owned by Agent 1*.  In both examples, the traits of Resource A (and thus its "nature") have very importantly changed.

Processes which transfer ownership include the concept of *gift*, but they're usually clearly definable *exchanges* with interdependent (mutually expected *and* required) simultaneous transfers of ownership of one or more resources in each direction.  These are extremely common interactions, and I hope VF will be able to represent them in ways which are efficiently interoperable with (and often *linked to*) processes of physical transformation and transmutation.

Of course, you could define *process* to refer strictly to physical resources; and while the Law of Conservation of Energy applies regardless, you could limit the term *process* to events which change the total quantity of one or more officially accounted resources.   However, I think that'd create an undesirable poverty of VF's expressive powers.  

Anyway, it's not an either/or between Process and Agreement.   An official Agreement can serve to represent, document and testify that a change of ownership *is mutually recognized*, and will be mutually respected moving forward.   That written Agreement is simply a representation of a *decision*, and *commitment*, which has either (1) already occurred or (2) *is created by the gathering of all required signatures*.

Of course I wouldn't expect everyone to describe every Agreement as a process, and many processes which transfer ownership don't have any official Agreement attached to them.  That's fine; people should of course be empowered to describe events at any levels of organizing and descriptive complexity they prefer.

**Comment by fosterlynn** [comment]
>> One thing that happens when putting transfers under a Process is that it is not clear what is an input and what is an output.

>Since transferring ownership only affects how rights get calculated and doesn't affect quantity (actually contained) of the resource, I don't think transfers would go as either inputs or outputs

Would you relate the transfer to the process that outputs the service though?  Somehow the service needs to know which transfer it was about.  It could be another named relationship, not inputOf or outputOf.

>I think fee comes for moving (virtual shipping) of currency units between accounts (addresses). IMO one could make pure VF transfer of ownership which would get only recorded in datasets of agents. Units wouldn't need to get moved between accounts at all.

I don't see where currency transfers are ever anything besides recording in the datasets of agents, whether possession or ownership or whatever.  There is no "movement" of bits or anything else, except in people's heads as a metaphor.  There could be other work in the area of validation, but that isn't movement.  So I guess I am agreeing?

>Ownership is a resource, and I see transferring ownership as a process.

We have tried making ownership (and other rights) directly into resources, and I think it is accurate in some way, as well as at least mostly accepted in the REA community, but it ended up being messy in the actual model.

>For example, Resource A with Location Y is not the same as Resource A in Location X; nor is Resource A owned by Agent 2 the same thing as Resource A owned by Agent 1. In both examples, the traits of Resource A (and thus its "nature") have very importantly changed.

Agree.  Although I can imagine exceptions, based on what people care about (location, owning agent).  Maybe some environmental resources?  Anyhow, agree basically.

>Of course, you could define process to refer strictly to physical resources; and while the Law of Conservation of Energy applies regardless, you could limit the term process to events which change the total quantity of one or more officially accounted resources. However, I think that'd create an undesirable poverty of VF's expressive powers.

Agree.

**Comment by gcassel** [comment]
> We have tried making ownership (and other rights) directly into resources, and I think it is accurate in some way, as well as at least mostly accepted in the REA community, but it ended up being messy in the actual model.

I don't know where the messiness arose, Lynn, but I hope that agents will ultimately be able to link ownership data to tradeable goods and services by either entering *or* hyperlinking unique owner IDs to relevant descriptive elements, potentially including RDF frames.  BTW, I use IDs in the plural there because I'd prefer for co-ownership to be innately enabled, even if that "only" enables strictly "flat" co-ownership, which is what I broadly prefer anyway for *intentional assignment of ownership*.  (Non-equal ownership can be of course developed in many ways, including the division of countable or measurable resources into equal and separately-owned shares.)

I note that a [Collective Media Resource Description Framework](https://github.com/gcassel/Models/blob/master/collective-resource-description-framework.md) is a prominent component of my [P2P Modular Organizing Framework](https://docs.google.com/drawings/d/1KZpc4_98IrJ0cjcFpkL5TcBug63fsTrT6i5eL2j5z80/edit?usp=sharing); however that media RDF refers only to the traits of *media items*, which might or might not represent tradeable goods and services.  Therefore I haven't addressed ownership per se at that level of organizing detail, although *media access and edit rights* are central to the model.   I hope to eventually put goods and services language *in* media items which are attached to such RDFs; and that "goods and services language" could of course occur in many ways, including a nested RDF or as machine-readable language.  (I remember that Bob has written eloquently about the potentials of machine-readable language via "a vocabulary, text messages, and a bot".)

I'm just passing through and dropping thoughts on the fly, but feel free of course to follow up anytime in any way.  Thanks for your continuing work!

**Comment by fosterlynn** [comment]
I was looking at some of McCarthy's recent writings, and saw an interesting option that might fit into this discussion: `trigger`, which is a relationship between Commitments, where one triggers another.  We would need it between EconomicEvents too.  One place this might come in useful is for example when a receipt of a resource triggers a transfer of ownership of the resource (FOB destination).  Still thinking about it, but thought I'd  record it here anyway.

I'm also wondering if we want to broaden Agreement into other kinds of bundles of commitments and/or events.  It is already stretching the definition of Agreement when we use it on retail exchanges.  And there is the use case of transaction fees for currency transfers.

Will think about these in the context of continuing work on transfers, still trying to nail that down into something completely coherent and as simple as possible..... ;)

**Comment by gcassel** [comment]
Yikes sorry I didn't even notice til now that I accidentally closed this Issue 19 hours ago.  Thanks @fosterlynn for reopening it!

**Comment by gcassel** [comment]
FWIW, I've adapted McCarthy's 'trigger' concept into Modular Organizing Terminology: [trigger](https://github.com/gcassel/Modular-Organizing-Terminology/blob/master/terms/trigger.md) .  It's a placeholder definition, but it's a deeply important concept-- so thanks for sharing it!

**Comment by fosterlynn** [comment]
>Transfer of a crypto-currency and the fee for the transfer to the 3rd party supporting the transfer (miner, server operator).

I have added `vf:triggeredBy` to the latest PR for transfer.  It works nicely for a transfer of a currency triggering the transfer of a fee.

**Comment by fosterlynn** [comment]
Superseded by v.3
