### ISSUE TITLE
rawgit links will break soon

### ISSUE THREAD

**Issue by ahdinosaur** [valueflows/valueflows#553]
a story about the rawgit sunset: https://rawgit.com/ :city_sunset: 

code to be fixed: https://github.com/valueflows/valueflows/search?q=rawgit&unscoped_q=rawgit

since we're mostly using rawgit to link to images, we could probably link directly to images within the gitbook. otherwise we can maybe use https://raw.githack.com/ instead.

:heart:

**Comment by bhaugen** [comment]
@ahdinosaur thanks for the warning!

**Comment by bhaugen** [comment]
Experiment: 
![3x](https://user-images.githubusercontent.com/117439/62943522-474a9d00-bda0-11e9-82bb-1f59a4f24556.png)

**Comment by bhaugen** [comment]
Here's an experiment: 
![image from github](https://github.com/valueflows/valueflows/blob/master/release-doc-in-process/coffee-oliveoil-flows.png)

Another: 
![image from github](https://raw.githubusercontent.com/valueflows/valueflows/master/release-doc-in-process/claim.png)

I tried what looked like a direct link to the image for the first one: https://github.com/valueflows/valueflows/blob/master/release-doc-in-process/coffee-oliveoil-flows.png
That did not work.

For the second one I used https://raw.githubusercontent.com/valueflows/valueflows/master/release-doc-in-process/claim.png
That worked.

Did I misunderstand something there?

I'm reluctant to switch to raw.githack because there again we are riding on some volunteer project, lovely though those volunteers are. I didn't know we were doing that in the first place, but then sometimes I am out of touch with reality...

So looks like we need to learn how to properly serve images in gitbooks...

**Comment by bhaugen** [comment]
Let's see if I can understand something.

> For the second one I used https://raw.githubusercontent.com/valueflows/valueflows/master/release-doc-in-process/claim.png
That worked.

And that did not use rawgit, right? And so would not need raw.githack? But is it safe to use in the gitbook pages? Or would some other expression be better? Still seems vaguely hacky...

**Comment by ahdinosaur** [comment]
i'd first try to update the links like https://github.com/valueflows/valueflows/commit/54f9c75a35575d8fa6e9e20a8f0c1e90396b5bf4, i reckon that should work with GitBook. otherwise yeah, the latter `raw.githubusercontent.com` is probably okay. :smiley_cat:

**Comment by bhaugen** [comment]
So the change seems to be:
* Starting with 
    * https://github.com/valueflows/valueflows/blob/master/release-doc-in-process/coffee-oliveoil-flows.png
* replace github.com with raw.githubusercontent.com
* remove blob/
* results in:
    * https://raw.githubusercontent.com/valueflows/valueflows/master/release-doc-in-process/coffee-oliveoil-flows.png

**Comment by bhaugen** [comment]
I made and pushed those changes. Found one anomaly:
* https://valueflo.ws/specification/diagrams/vowl.html

**Comment by bhaugen** [comment]
Fixed the svg file by doing:
```
[VF OWL picture](http://mikorizal.org/all-vf-vowl.svg)
```

[VF OWL picture](http://mikorizal.org/all-vf-vowl.svg)

**Comment by fosterlynn** [comment]
Fixed.
