### ISSUE TITLE
RDF/Owl schema: arrays vs singular values

### ISSUE THREAD

**Issue by orthecreedence** [valueflows/valueflows#623]
Currently in the Owl spec from what I can tell there's no concept of whether a value is singular or one-to-many. For instance `RecipeProcess::processClassifiedAs` is labeled as an array in both the JSON/GQL schemas, but I see nothing that differentiates it from other values that show up as singular in those schemas.

One thing I've come across in my research is that `owl:FunctionalProperty` might be used to signify a *singular* value, but by default all values can be multiple. I've also read that `owl:FunctionalProperty` is additive such that it can be specified alongside `owl:ObjectProperty`.

It might make sense to define which fields in the classes are singular. As a usual caveat, I don't know much about RDF/owl so I might be totally off-base by suggesting `owl:FunctionalProperty` to accomplish this.

**Comment by fosterlynn** [comment]
> As a usual caveat, I don't know much about RDF/owl

And my usual caveat: Nor do I, just "book learning" and a few toy examples.  @elf-pavlik has provided a lot of the rdf/owl expertise for ValueFlows, and has been my teacher in that respect. :)

My reading of the documentation is like yours.  We have been a bit loose thus far in the rdf spec, choosing to define some of the constraints in the UML, text, and/or the graphql spec.  Since you are using the turtle spec to drive your work, you have run into this.  I agree, let's tighten up the turtle spec so it can be used to generate other formats, as well as be more informative.  I see that ActivityStreams and foaf use FunctionalProperty.

Or hmmm, looks like we may be able to use owl:cardinality for all the required properties that have 1.... ref #624 .

I'll dig a little more, and do a PR.

**Comment by orthecreedence** [comment]
I was also wondering if cardinality could be used for array vs singular initially as well. It seems to be able to define "0 or more" "at most 1" and "exactly 1" which seems to solve the array, optional, required fields respectively. I was not able to confirm this as being a pattern used in the wild in my research though.

**Comment by fosterlynn** [comment]
Looked around some more, also not seeing cardinality in the wild. Looks like it is part of OWL 2 only - but I'm not sure if that means we should avoid it.  Still investigating...

**Comment by orthecreedence** [comment]
Sounds like you're have about the same amount of luck I did. I'll keep looking too.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/valueflows/-/issues/623.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
