### ISSUE TITLE
Queston on modeling salary

### ISSUE THREAD

**Issue by orthecreedence** [valueflows/valueflows#628]
I'm noticing ways of compensating work by an hourly amount or by deliverable, but I'm wondering if there is an idiomatic way to model a salaried worker. Would it essentially be creating an EconomicEvent with an action "work" on the 15th and last of every month?

**Comment by bhaugen** [comment]
Will be connected to that other thread about overhead work. Good stuff
to discuss, after Lynn and I talk a bit.

**Comment by fosterlynn** [comment]
>Would it essentially be creating an EconomicEvent with an action "work" on the 15th and last of every month?

That seems totally OK to me for some situations.  And you could always denominate work events in different units, month or week or day.  But that might not work for everyone.  For example you might also want to know what work was done on what processes, just for your operational info, maybe to improve your processes.  Then you wouldn't want to duplicate it (but that is a discussion for your other issue).  

Or you could treat the salary side as just the salary, since it theoretically isn't directly related to how much work or what kind of work you have done anyhow.  And just create transfers of money twice a month based on what the salary is, which is based on a prior agreement.

**Comment by orthecreedence** [comment]
> Or you could treat the salary side as just the salary, since it theoretically isn't directly related to how much work or what kind of work you have done anyhow. And just create transfers of money twice a month based on what the salary is, which is based on a prior agreement.

Ok, right. I'm kind of leaning this direction, mainly because labor costs are going to be bucketed into both `hours` and `hours * wage`. Final costs are going to be based on waged hours, but I want to track hours independently for the possible future case where all wages are 0 but knowing total labor hours might still be useful economic information.

Thanks for the input here.
