### ISSUE TITLE
Linked Data Browser loses /linked-data-browser/ URL segment

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#85]
When I go to http://dinosaur.is/linked-data-browser/
and paste this into the "focus @id" widget
http://nrp.webfactional.com/api/agent-jsonld/
and hit enter or move the cursor from the widget, this is what the URL turns into:
http://dinosaur.is/?viewId=nodeList&focusId=http%3A%2F%2Fnrp.webfactional.com%2Fapi%2Fagent-jsonld%2F
Then if I click on that, I get the lovely "dinosaur is  a hippie hacker" page.

**Comment by ahdinosaur** [comment]
lol, thanks for the bug report. :)

**Comment by ahdinosaur** [comment]
fixed with https://github.com/valueflows/linked-data-browser/commit/94dcc1b2faf435dc892ea00b6c37a8acedc7618f.

also, i brought `linked-data-browser` into the `valueflows` org, check it out: http://valueflows.github.io/linked-data-browser/. (also at https://valueflo.ws/linked-data-browser/ via [proxy](https://github.com/valueflows/valueflo.ws/commit/f3bee47a51768a0fed62b9800bf6bafeb455cc8e), but it will error if you try to access anything not over https).

**Comment by bhaugen** [comment]
Thx
