### ISSUE TITLE
Broken bike repair issues

### ISSUE THREAD

**Issue by bhaugen** [valueflows/valueflows#95]
Preliminary comments on this use case: https://github.com/valueflows/valueflows/blob/master/use-cases/circular-economy/broken-bike-repair.md
- I would separate this resource:
  - Dave’s bike shop that provides a repair service
- into two resources:
  - Dave's bike shop
  - Repair service (which I'll detail out more below)

Dave's bike shop could mean a physical facility (maybe a building or some rooms in a building)
or it could be a business. If it's a physical facility, it is a resource. But it can't do anything like provide repair service, that requires an agent. If it's a business, it's an agent, and can provide repair services.

Otherwise, Dave the person provides the repair service.

The process of repair is really interesting. It is one of those cases where the same resource is both an input (the broken bike) and an output (the repaired bike, but it's still the same bike, but maybe with some new parts).

So I think the process should go like this:
### Resource flows
- Input
  - John gives Dave the bike
  - Dave gets some new parts
  - Dave does some work, applying his repair skills
- Process
  - Dave repairs bike, using the new parts and his repair skills
- Output
  - Repaired bike
  - Repair service
- Exchange
  - Dave transfers the repair service to John, which includes Dave's work and the new parts
    - (Literally, Dave gives John a bill that includes both of those items.)
  - John pays Dave for the repair service
### Questions
- _Is this a process of repair or a temporary exchange?_
  - The repair is a process, the exchange is for the repair service
- _Is the repair service a property of the shop or a skill of Dave?_
  - The repair service is provided by Dave, but includes his work and some new parts
    - (That is, unless the shop is a business, in which case the shop might provide the service, which would include Dave's skilled work.)
  - In either case, the service provider is an agent and the service is a combination, package, or bundle of some work and some parts, all of which are resources. The service itself would be defined by a resource type.

Resources can be instantiated as objects, or may not be worth instantiating as objects. Dave's work would be an input value flow, defined by a resource type (maybe Bike Repair Skills), but would probably not be instantiated as a separate resource. It's more like an implicit resource. _Please let me know if that makes sense or needs more discussion or work._

@fosterlynn did a recent service package for 3D printers that was a lot like the bike service package. Maybe she can help detail this out a bit more?

**Comment by fosterlynn** [comment]
@pmackay @bhaugen Cool.  OK, I'm going to try out a level of detail down, for discussion.  And I'm sure when @elf-pavlik  has time, he'll have more....  :)

I'm going to assume that Dave's Bike Shop is an agent.  Even if it is just Dave doing the work, the business or organization likely will have its own agency for many things.  Even an informally organized OVN will have agency. The facility is a resource, as Bob pointed out.  For simplicity, let's assume for now that Dave has the parts on hand.  So a Purchase Exchange has already happened that involved Dave's Bike Shop exchanging the part and probably others for $ with the part supplier.  Or maybe he bartered something, or maybe he still owes the $, or whatever.

Input:
* Resource: John's bike, Value Flow (aka Economic Event): To Be Changed (the one we need a better name for), Involved Agent: John
* Resource: The bike shop, Value Flow: Use for 2 hours, Involved Agent: Dave's Bike Shop
* Resource: New pedal (a part), Value Flow: Consume 1 pedal, Involved Agent: Dave's Bike Shop
* Resource Type: Repair work, Value Flow: Work 2 hours, Involved Agent: Dave

Process: Dave repairs bike

Output:
* Resource: John's bike, Value Flow: Changed (need better name), Involved Agent: Dave's Bike Shop
* Resource: Repair service, Value Flow: Create, Involved Agent: Dave's Bike Shop

Exchange (2 connected transfers):

Transfer:
* Resource: Repair service, Value Flow: Give 1 service, Involved Agent: Dave's Bike Shop
* Resource: Repair service, Value Flow: Receive 1 service, Involved Agent: John

Transfer:
* Resource: Cash, Value Flow: Give $50, Involved Agent: John
* Resource: Cash, Value Flow: Receive $50, Involved Agent: Dave's Bike Shop

(This with the Transfers is part of what I am doing in NRP right now, separating out exchange and transfer, and separating transfer into give and receive flows..  Not proven in code yet.  But it makes the value flows consistent, you need both events so there is an edge on either side of the resource as it flows.  Similar to To Be Changed and Changed, you need an edge on either side of the process.)

A vague question I have on the repair service is do we want to bundle the process inputs into the service.  But I think we do.  Then on the bill, Dave will need to track back into the process to list the line items and what each costs.

So another interesting thing to think about is what happens to the money and why the value flow is useful.  Once the money is received by Dave's Bike Shop, it could get distributed back along the flow.  This is what happens in OVNs.  So Dave gets paid something per hour for his work, the supplier or the Dave's Bike Shop gets paid for the part, maybe Dave's Bike Shop gets something so the rent can be paid, etc.  Or maybe several people contributed to the rent, and they will get something to repay that.

I'm not finding the need to have an exchange or transfer so that John can give Dave's Bike Shop the dodgy bike.  But say if John had to know where the bike was because he has several that he uses to deliver pizza, then something would need to be recorded.  There's another whole discussion to be had (or continued) around change of location and/or change of possession.  

P.S. I'd like to move to UK just so I can use the word "dodgy" !

**Comment by fosterlynn** [comment]
>@fosterlynn did a recent service package for 3D printers that was a lot like the bike service package. 

Just for reference, this bundled use of the 3D printer (in hours), consumables (filament in grams), help from a technician (in hours), and $1.50 per hour of printer use to a fund for future maintenance needs of the printer, into a service resource.  With some variations for context, like people working on a Sensorica project vs people with a FabLab membership.   I'll look back at it if anyone is interested in more detail, but it was pretty experimental in terms of the model.  It was our first use case with a mix of processes and exchanges, and I hardcoded a lot of it to start to get learnings towards the model.

**Comment by pmackay** [comment]
@fosterlynn sounds like you and @bhaugen are contradicting yourselves :) I'm a bit confused by the bike shop being an Agent. Can you expand a bit on why you've approached it that way? The definition that only Agents **do** things seems logical to me.. 

Also about going a "level deeper" - is there always likely to be varying layers of details on this kind of modelling (depending on use case)? Are there times when a simpler model will do? 

FYI, I'm more interested currently in how the VF language can be used to model the entities, how to define them. I'm definitely interested in the exchange/flow of data as well, but developing a common approach to representing the bike shop, bike, Dave who can do repairs, etc is needed for the stuff we're working on.

**Comment by fosterlynn** [comment]
>@fosterlynn sounds like you and @bhaugen are contradicting yourselves :)

We probably do that regularly, sorry about that. :)  Where did we do that above? We'll try to resolve it.

>about going a "level deeper" 

Just meant more detail on the same use case, closer to a vocab rendering, not trying to make it more complex.  For example, I added the flows (economic events in the REA model) because we have found them to be essential to the model, you need a place to have info about the edges/flows that happen around a process and resources that are input or output of a process.

> I'm more interested currently in how the VF language can be used to model the entities, how to define them. I'm definitely interested in the exchange/flow of data as well

I'm trying to understand that better, I'm not sure how to think of them separately.  I can give a try at a model - RDF or UML.  We have some static ones already, I'll look for them.  Or I can do something for this use case, which tends to ground things nicely.

>entities, how to define them

Definitions  :+1: 

And just to note, we as a group haven't carefully defined the entities in the exchange and process use cases, although we've had a bunch of preliminary discussions in hairy detail in gitter and various issues.  The model we use in NRP (derived from REA) will be a big input.  (https://github.com/valnet/valuenetwork/wiki/Links - although some of these are broken)  It is a radically simplified model with some history behind it.  But from the experience with ValueFlows Agent (the only place we have come to basic agreement as a ValueFlows group yet), there will be other inputs, as well as lots of refinement to the NRP-REA model. Which is great.

So you're jumping in to the fire, to some extent.  But I'm hoping you like it there and have time for it! :)  (I'm happy to work on your use cases though, irrespective of how much you want to get into the action!)

**Comment by pmackay** [comment]
> We probably do that regularly, sorry about that. :) Where did we do that above? We'll try to resolve it.

@bhaugen suggests the repair shop is a Resource. You've suggested it is an Agent. Or is that about considering Dave and the shop as one entity?

**Comment by bhaugen** [comment]
I tried to clarify that, but obviously failed. 

If by "repair shop", you mean a physical building or room(s) in a building, it's a resource.

If you mean "repair shop" as a organization where Dave works, it's an agent.

**Comment by bhaugen** [comment]
But @fosterlynn and I do like to disagree with each other from time to time. Keeps us on our toes.

**Comment by pmackay** [comment]
OK so maybe need to say:

"Dave's bike shop" - physical building.
"Dave's Bikes" - his business. An organisation (Agent?) that offers services. Is there benefit in splitting the Organisation/business from the person? Perhaps if it is a larger business with multiple people.

**Comment by fosterlynn** [comment]
@pmackay Yes, I have the shop in two places, once as a resource (the physical space) and once as an agent (Dave's Bike Shop > will make Dave's Bikes), an organization which probably has it's own checking account for example.  So if Dave's Bike Shop the agent moved to a different space, nothing would change about the agent itself - just its relationships to a location, etc.  

>But @fosterlynn and I do like to disagree with each other from time to time. Keeps us on our toes.

Indeed! :)

**Comment by fosterlynn** [comment]
> Is there benefit in splitting the Organisation/business from the person? 

@pmackay I think there is.  In this use case, they seem like separate agents, with a relationship to each other.  Probably have separate checking accounts, file taxes separately even if there isn't a corporation or something legal involved, at least in the US I think you have to do that.  And they have different names in our example,a good indication.

When you get down to something like timebanks or very informal barter systems, there is less likely to be an organization involved.  People just do work for credits in the system.  But are unlikely to have a shop with a different name in those situations.

Does this seem right to you?

**Comment by fosterlynn** [comment]
> Is there benefit in splitting the Organisation/business from the person? 

Additional thought: VF vocab wouldn't make anyone do it one way or another, people can define their own people and organizations as it works best for their situation.  Not that it isn't a useful discussion, I think it is.

**Comment by bhaugen** [comment]
@pmackay - one more comment, to underscore what Lynn wrote above. You asked:
>  going a "level deeper" - is there always likely to be varying layers of details on this kind of modelling (depending on use case)? Are there times when a simpler model will do?

We've tended to go deeper and deeper in a lot of our recent use case analyses, which I think has been useful. But in practice, when working in real situations with real people, we use the details that they need and make sense to them, and omit those that don't, as long as the flows work.

**Comment by pmackay** [comment]
@fosterlynn I can see the potential of splitting them but I guess it depends on the use case one is trying to solve? In my bike repair one, it may not be important, because from the perspective of John with the bike, he just wants to find a place to repair it, so separating the business and person is not essential. But for other kinds of value applications it could be.

**Comment by bhaugen** [comment]
An economic network needs to consider the perspective of Dave and the Bike Shop (assuming it is a business) as well as John. (Assuming Dave and the Bike Shop are members of a network.)

**Comment by fosterlynn** [comment]
@pmackay yes from John's perspective, only the exchange is needed, and only Dave's Bikes is needed as an agent.  (Assuming they are separated)  Dave himself is part of a process inside Dave's Bikes but not outward facing.  Or I suppose it could be Dave outward facing and Dave's Bikes is more just how Dave gets things done.  Whichever, in any case only one agent is needed from John's perspective.

@bhaugen So if this were a network that does only exchanges, like FairCoop (as far as I understand) or Mutual Aid Network in Madison, then internal processes wouldn't be important to capture. and only agents that participate in exchanges would be needed in a system.  But if it is like Sensorica, where people can plug into processes anywhere along the stream of value creation, then all of that would need to be captured as part of the operations of the network.

**Comment by fosterlynn** [comment]
I updated my posting near the top to include another output from the process, which is the used component, to better start thinking in terms of circular economy.

So in a network, that could show up as a resource to be re-used in some way, or go into a recycling process or whatever.  This could a reason a network might want to expose processes even if they are not managed by the network but by a node in the network internally.  (Just thinking out loud.)

**Comment by fosterlynn** [comment]
Resolved for v.3, please re-open if needed.
